//! Generated clients route methods.

use crate::{routes, types, Client, Error, ResponseValue};
use progenitor_client::encode_path;

/// Generated `clients` route methods on [`crate::Client`].
///
/// Client-owned request policy on [`crate::Client`]:
/// - idempotency via [`crate::Client::with_idempotency_key`] (default: UUID v4 per request)
/// - `testmode` query via [`crate::Client::with_testmode`] on operations that support it
///
/// The resolved idempotency key is returned on the response envelope
/// ([`crate::ResponseValue`] / [`crate::ResponseEnvelope`]).
#[allow(clippy::all)]
impl Client {
    /// List clients
    ///
    /// Retrieve a list of all clients linked to your account.
    ///
    /// The results are paginated.
    ///
    /// Sends a `GET` request to `/clients`
    ///
    /// Arguments:
    /// - `embed`: This endpoint allows embedding related API items by appending the following values via the `embed` query string
    /// parameter.
    /// - `from`: Provide an ID to start the result set from the item with the given ID and onwards. This allows you to paginate the
    /// result set.
    /// - `limit`: The maximum number of items to return. Defaults to 50 items.
    pub async fn list_clients<'a>(
        &'a self,
        embed: Option<&'a str>,
        from: Option<&'a str>,
        limit: Option<::std::num::NonZeroU64>,
    ) -> Result<ResponseValue<types::ListClientsResponse>, Error<types::ErrorResponse>> {
        let url = self.endpoint("/clients");
        #[allow(unused_mut)]
        let (request, resolved_idempotency_key) = self.request(::reqwest::Method::GET, url)?;
        #[allow(unused_mut)]
        let mut request = request
            .query(&progenitor_client::QueryParam::new("embed", &embed))
            .query(&progenitor_client::QueryParam::new("from", &from))
            .query(&progenitor_client::QueryParam::new("limit", &limit))
            .build()?;
        let response = self.send(request, routes::Operation::ListClients).await?;
        routes::response::json(
            response,
            &[200u16],
            &[400u16, 404u16, 429u16],
            &resolved_idempotency_key,
        )
        .await
    }

    /// Get client
    ///
    /// Retrieve a single client by its ID.
    ///
    /// Sends a `GET` request to `/clients/{organizationId}`
    ///
    /// Arguments:
    /// - `organization_id`: Provide the ID of the related organization.
    /// - `embed`: This endpoint allows embedding related API items by appending the following values via the `embed` query string
    /// parameter.
    pub async fn get_client<'a>(
        &'a self,
        organization_id: &'a types::OrganizationToken,
        embed: Option<&'a str>,
    ) -> Result<ResponseValue<types::GetClientResponse>, Error<types::ErrorResponse>> {
        let url = self.endpoint(format_args!(
            "/clients/{}",
            encode_path(&organization_id.to_string())
        ));
        #[allow(unused_mut)]
        let (request, resolved_idempotency_key) = self.request(::reqwest::Method::GET, url)?;
        #[allow(unused_mut)]
        let mut request = request
            .query(&progenitor_client::QueryParam::new("embed", &embed))
            .build()?;
        let response = self.send(request, routes::Operation::GetClient).await?;
        routes::response::json(
            response,
            &[200u16],
            &[404u16, 429u16],
            &resolved_idempotency_key,
        )
        .await
    }

    /// Create client link
    ///
    /// Link a new or existing organization to your OAuth application, in effect creating a new client. The response
    /// contains a `clientLink` where you should redirect your customer to.
    ///
    /// ## Redirecting the Customer
    ///
    /// The `clientLink` URL behaves similarly to a standard OAuth authorization URL. Therefore, after receiving the
    /// `clientLink` URL in the API response, you need to **append the following query parameters** *before* redirecting
    /// the customer:
    ///
    ///  `client_id` _string (required)_
    ///
    ///   The client ID you received when you registered your OAuth app. The ID starts with `app_`. For example:
    ///   `app_abc123qwerty`.
    ///
    ///  `state` _string (required)_
    ///
    ///   A random string **generated by your app** to prevent CSRF attacks. This will be reflected in the `state` query
    ///   parameter when the user returns to the `redirect_uri` after authorizing your app.
    ///
    ///  `scope` _string (required)_
    ///
    ///   A space-separated list of permissions ('scopes') your app requires. See the
    ///   [permissions list](https://docs.mollie.com/docs/permissions) for more information about the available
    ///   scopes.
    ///
    ///   We recommend at least : `onboarding.read onboarding.write`
    ///
    ///  `approval_prompt` _string_
    ///
    ///   Can be set to `force` to force showing the consent screen to the merchant, *even when it is not necessary*. If you
    ///   force an approval prompt and the user creates a new authorization, previously active authorizations will be
    ///   revoked.
    ///
    ///   Possible values: `auto` `force` (default: `auto`)
    ///
    /// ### Example of a Complete Redirect URL
    ///
    /// After adding the above url parameter your URL will look something like this and you can redirect your client to this
    /// page:
    ///
    /// ```text
    /// https://my.mollie.com/dashboard/client-link/{id}?client_id={your_client_id}&state={unique_state}&scope=onboarding.read%20onboarding.write
    /// ```
    ///
    /// ## Error Handling
    ///
    /// Error handling is also dealt with similar to the [Authorize](https://docs.mollie.com/reference/authorize) endpoint:
    /// the customer is redirected back to your app's redirect URL with the `error` and `error_description` parameters added
    /// to the URL.
    ///
    /// > 🚧
    /// >
    /// > A client link must be used within 30 days of creation. After that period, it will expire and you will need to create a new client link.
    ///
    /// Sends a `POST` request to `/client-links`
    ///
    /// Arguments:
    pub async fn create_client_link<'a>(
        &'a self,
        body: &'a types::ClientLinkRequest,
    ) -> Result<ResponseValue<types::ClientLinkResponse>, Error<types::ErrorResponse>> {
        let url = self.endpoint("/client-links");
        #[allow(unused_mut)]
        let (request, resolved_idempotency_key) = self.request(::reqwest::Method::POST, url)?;
        #[allow(unused_mut)]
        let mut request = request.json(&body).build()?;
        let response = self
            .send(request, routes::Operation::CreateClientLink)
            .await?;
        routes::response::json(
            response,
            &[201u16],
            &[404u16, 422u16, 429u16],
            &resolved_idempotency_key,
        )
        .await
    }
}
