//! Central operation metadata for generated route hooks.

use progenitor_client::OperationInfo;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Operation {
    OauthGenerateTokens,
    OauthRevokeTokens,
    ListBalances,
    GetBalance,
    GetPrimaryBalance,
    GetBalanceReport,
    ListBalanceTransactions,
    ListSettlements,
    GetSettlement,
    GetOpenSettlement,
    GetNextSettlement,
    ListSettlementPayments,
    ListSettlementCaptures,
    ListSettlementRefunds,
    ListSettlementChargebacks,
    ListInvoices,
    GetInvoice,
    ListPermissions,
    GetPermission,
    GetOrganization,
    GetCurrentOrganization,
    GetPartnerStatus,
    ListProfiles,
    CreateProfile,
    GetProfile,
    DeleteProfile,
    UpdateProfile,
    GetCurrentProfile,
    GetOnboardingStatus,
    SubmitOnboardingData,
    ListCapabilities,
    ListClients,
    GetClient,
    CreateClientLink,
    ListWebhooks,
    CreateWebhook,
    GetWebhook,
    DeleteWebhook,
    UpdateWebhook,
    TestWebhook,
    GetWebhookEvent,
    ListConnectBalanceTransfers,
    CreateConnectBalanceTransfer,
    GetConnectBalanceTransfer,
    ListPayments,
    CreatePayment,
    GetPayment,
    CancelPayment,
    UpdatePayment,
    ReleaseAuthorization,
    ListUnmatchedCreditTransfers,
    GetUnmatchedCreditTransfer,
    MatchUnmatchedCreditTransfer,
    ReturnUnmatchedCreditTransfer,
    CreateSession,
    GetSession,
    ListMethods,
    ListAllMethods,
    GetMethod,
    EnableMethod,
    DisableMethod,
    EnableMethodIssuer,
    DisableMethodIssuer,
    ListRefunds,
    CreateRefund,
    GetRefund,
    CancelRefund,
    ListAllRefunds,
    ListChargebacks,
    GetChargeback,
    ListAllChargebacks,
    ListCaptures,
    CreateCapture,
    GetCapture,
    RequestApplePayPaymentSession,
    ListPaymentLinks,
    CreatePaymentLink,
    GetPaymentLink,
    DeletePaymentLink,
    UpdatePaymentLink,
    GetPaymentLinkPayments,
    ListTerminals,
    GetTerminal,
    TerminalsListPairingCodes,
    TerminalsRequestPairingCode,
    TerminalsGetPairingCode,
    TerminalsRevokePairingCode,
    PaymentListRoutes,
    PaymentCreateRoute,
    PaymentGetRoute,
    ListCustomers,
    CreateCustomer,
    GetCustomer,
    DeleteCustomer,
    UpdateCustomer,
    ListCustomerPayments,
    CreateCustomerPayment,
    ListMandates,
    CreateMandate,
    GetMandate,
    RevokeMandate,
    ListSubscriptions,
    CreateSubscription,
    GetSubscription,
    CancelSubscription,
    UpdateSubscription,
    ListAllSubscriptions,
    ListSubscriptionPayments,
    ListSalesInvoices,
    CreateSalesInvoice,
    GetSalesInvoice,
    DeleteSalesInvoice,
    UpdateSalesInvoice,
    ListBusinessAccounts,
    GetBusinessAccount,
    ListBusinessAccountTransactions,
    GetBusinessAccountTransaction,
    CreateTransfer,
    GetTransfer,
    VerifyPayee,
    ListPayouts,
    CreatePayout,
    GetPayout,
    CancelPayout,
}

impl Operation {
    /// Return the OpenAPI operation id for this route.
    pub(crate) const fn id(self) -> &'static str {
        match self {
            Self::OauthGenerateTokens => "oauth_generate_tokens",
            Self::OauthRevokeTokens => "oauth_revoke_tokens",
            Self::ListBalances => "list_balances",
            Self::GetBalance => "get_balance",
            Self::GetPrimaryBalance => "get_primary_balance",
            Self::GetBalanceReport => "get_balance_report",
            Self::ListBalanceTransactions => "list_balance_transactions",
            Self::ListSettlements => "list_settlements",
            Self::GetSettlement => "get_settlement",
            Self::GetOpenSettlement => "get_open_settlement",
            Self::GetNextSettlement => "get_next_settlement",
            Self::ListSettlementPayments => "list_settlement_payments",
            Self::ListSettlementCaptures => "list_settlement_captures",
            Self::ListSettlementRefunds => "list_settlement_refunds",
            Self::ListSettlementChargebacks => "list_settlement_chargebacks",
            Self::ListInvoices => "list_invoices",
            Self::GetInvoice => "get_invoice",
            Self::ListPermissions => "list_permissions",
            Self::GetPermission => "get_permission",
            Self::GetOrganization => "get_organization",
            Self::GetCurrentOrganization => "get_current_organization",
            Self::GetPartnerStatus => "get_partner_status",
            Self::ListProfiles => "list_profiles",
            Self::CreateProfile => "create_profile",
            Self::GetProfile => "get_profile",
            Self::DeleteProfile => "delete_profile",
            Self::UpdateProfile => "update_profile",
            Self::GetCurrentProfile => "get_current_profile",
            Self::GetOnboardingStatus => "get_onboarding_status",
            Self::SubmitOnboardingData => "submit_onboarding_data",
            Self::ListCapabilities => "list_capabilities",
            Self::ListClients => "list_clients",
            Self::GetClient => "get_client",
            Self::CreateClientLink => "create_client_link",
            Self::ListWebhooks => "list_webhooks",
            Self::CreateWebhook => "create_webhook",
            Self::GetWebhook => "get_webhook",
            Self::DeleteWebhook => "delete_webhook",
            Self::UpdateWebhook => "update_webhook",
            Self::TestWebhook => "test_webhook",
            Self::GetWebhookEvent => "get_webhook_event",
            Self::ListConnectBalanceTransfers => "list_connect_balance_transfers",
            Self::CreateConnectBalanceTransfer => "create_connect_balance_transfer",
            Self::GetConnectBalanceTransfer => "get_connect_balance_transfer",
            Self::ListPayments => "list_payments",
            Self::CreatePayment => "create_payment",
            Self::GetPayment => "get_payment",
            Self::CancelPayment => "cancel_payment",
            Self::UpdatePayment => "update_payment",
            Self::ReleaseAuthorization => "release_authorization",
            Self::ListUnmatchedCreditTransfers => "list_unmatched_credit_transfers",
            Self::GetUnmatchedCreditTransfer => "get_unmatched_credit_transfer",
            Self::MatchUnmatchedCreditTransfer => "match_unmatched_credit_transfer",
            Self::ReturnUnmatchedCreditTransfer => "return_unmatched_credit_transfer",
            Self::CreateSession => "create_session",
            Self::GetSession => "get_session",
            Self::ListMethods => "list_methods",
            Self::ListAllMethods => "list_all_methods",
            Self::GetMethod => "get_method",
            Self::EnableMethod => "enable_method",
            Self::DisableMethod => "disable_method",
            Self::EnableMethodIssuer => "enable_method_issuer",
            Self::DisableMethodIssuer => "disable_method_issuer",
            Self::ListRefunds => "list_refunds",
            Self::CreateRefund => "create_refund",
            Self::GetRefund => "get_refund",
            Self::CancelRefund => "cancel_refund",
            Self::ListAllRefunds => "list_all_refunds",
            Self::ListChargebacks => "list_chargebacks",
            Self::GetChargeback => "get_chargeback",
            Self::ListAllChargebacks => "list_all_chargebacks",
            Self::ListCaptures => "list_captures",
            Self::CreateCapture => "create_capture",
            Self::GetCapture => "get_capture",
            Self::RequestApplePayPaymentSession => "request_apple_pay_payment_session",
            Self::ListPaymentLinks => "list_payment_links",
            Self::CreatePaymentLink => "create_payment_link",
            Self::GetPaymentLink => "get_payment_link",
            Self::DeletePaymentLink => "delete_payment_link",
            Self::UpdatePaymentLink => "update_payment_link",
            Self::GetPaymentLinkPayments => "get_payment_link_payments",
            Self::ListTerminals => "list_terminals",
            Self::GetTerminal => "get_terminal",
            Self::TerminalsListPairingCodes => "terminals_list_pairing_codes",
            Self::TerminalsRequestPairingCode => "terminals_request_pairing_code",
            Self::TerminalsGetPairingCode => "terminals_get_pairing_code",
            Self::TerminalsRevokePairingCode => "terminals_revoke_pairing_code",
            Self::PaymentListRoutes => "payment_list_routes",
            Self::PaymentCreateRoute => "payment_create_route",
            Self::PaymentGetRoute => "payment_get_route",
            Self::ListCustomers => "list_customers",
            Self::CreateCustomer => "create_customer",
            Self::GetCustomer => "get_customer",
            Self::DeleteCustomer => "delete_customer",
            Self::UpdateCustomer => "update_customer",
            Self::ListCustomerPayments => "list_customer_payments",
            Self::CreateCustomerPayment => "create_customer_payment",
            Self::ListMandates => "list_mandates",
            Self::CreateMandate => "create_mandate",
            Self::GetMandate => "get_mandate",
            Self::RevokeMandate => "revoke_mandate",
            Self::ListSubscriptions => "list_subscriptions",
            Self::CreateSubscription => "create_subscription",
            Self::GetSubscription => "get_subscription",
            Self::CancelSubscription => "cancel_subscription",
            Self::UpdateSubscription => "update_subscription",
            Self::ListAllSubscriptions => "list_all_subscriptions",
            Self::ListSubscriptionPayments => "list_subscription_payments",
            Self::ListSalesInvoices => "list_sales_invoices",
            Self::CreateSalesInvoice => "create_sales_invoice",
            Self::GetSalesInvoice => "get_sales_invoice",
            Self::DeleteSalesInvoice => "delete_sales_invoice",
            Self::UpdateSalesInvoice => "update_sales_invoice",
            Self::ListBusinessAccounts => "list_business_accounts",
            Self::GetBusinessAccount => "get_business_account",
            Self::ListBusinessAccountTransactions => "list_business_account_transactions",
            Self::GetBusinessAccountTransaction => "get_business_account_transaction",
            Self::CreateTransfer => "create_transfer",
            Self::GetTransfer => "get_transfer",
            Self::VerifyPayee => "verify_payee",
            Self::ListPayouts => "list_payouts",
            Self::CreatePayout => "create_payout",
            Self::GetPayout => "get_payout",
            Self::CancelPayout => "cancel_payout",
        }
    }

    /// Build the hook metadata expected by progenitor-client.
    pub(crate) fn info(self) -> OperationInfo {
        OperationInfo {
            operation_id: self.id(),
        }
    }
}
