//! ISO 3166-1 alpha-2 country codes for Mollie request fields.
//!
//! Each entry is the ISO 3166-1 **alpha-2** code. English short names
//! follow the ISO 3166 Maintenance Agency (ISO 3166/MA). Optional
//! subdivision summaries describe categories coded in **ISO 3166-2**
//! (not full subdivision code lists).
//!
//! Mollie documents country fields (billing country, address `country`,
//! etc.) as ISO 3166-1 alpha-2. Generated OpenAPI types often keep these
//! as plain strings; validate with [`CountryCode`] first.
//!
//! See `docs/iso/iso-3166-1-alpha-2.md`.
//!
//! Regenerated by `scripts/generate_country_code.py`.
#![warn(missing_docs)]

use std::{fmt, str::FromStr};

use crate::{MollieError, MollieResult};

/// An ISO 3166-1 alpha-2 country code (`NL`, `DE`, `US`, …).
///
/// Use [`CountryCode::parse`] to validate strings before sending them as
/// `billingCountry`, address `country`, or similar Mollie fields.
///
/// # Columns
///
/// | Method | Content |
/// | --- | --- |
/// | [`as_str`](Self::as_str) | Entry (alpha-2 code) |
/// | [`name`](Self::name) | English short name (ISO 3166/MA) |
/// | [`subdivisions`](Self::subdivisions) | ISO 3166-2 subdivision categories (if any) |
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum CountryCode {
    /// Andorra — `AD`.
    ///
    /// ISO 3166-2: 7 parishes.
    Ad,
    /// United Arab Emirates — `AE`.
    ///
    /// ISO 3166-2: emirates.
    Ae,
    /// Afghanistan — `AF`.
    ///
    /// ISO 3166-2: 34 provinces.
    Af,
    /// Antigua and Barbuda — `AG`.
    ///
    /// ISO 3166-2: 6 parishes, 2 dependencies.
    Ag,
    /// Anguilla — `AI`.
    Ai,
    /// Albania — `AL`.
    ///
    /// ISO 3166-2: 12 counties.
    Al,
    /// Armenia — `AM`.
    ///
    /// ISO 3166-2: 1 city, 10 regions.
    Am,
    /// Netherlands Antilles (historically assigned; transitional ISO code) — `AN`.
    An,
    /// Angola — `AO`.
    ///
    /// ISO 3166-2: 18 provinces.
    Ao,
    /// Antarctica — `AQ`.
    Aq,
    /// Argentina — `AR`.
    ///
    /// ISO 3166-2: 1 city, 23 provinces.
    Ar,
    /// American Samoa — `AS`.
    As,
    /// Austria — `AT`.
    ///
    /// ISO 3166-2: 9 states.
    At,
    /// Australia — `AU`.
    ///
    /// ISO 3166-2: 6 states, 2 territories.
    Au,
    /// Aruba — `AW`.
    Aw,
    /// Åland Islands — `AX`.
    Ax,
    /// Azerbaijan — `AZ`.
    ///
    /// ISO 3166-2: 1 autonomous republic, 11 municipalities, 66 rayons.
    Az,
    /// Bosnia and Herzegovina — `BA`.
    ///
    /// ISO 3166-2: entities, 1 district with special status.
    Ba,
    /// Barbados — `BB`.
    ///
    /// ISO 3166-2: 11 parishes.
    Bb,
    /// Bangladesh — `BD`.
    ///
    /// ISO 3166-2: 8 divisions, 64 districts.
    Bd,
    /// Belgium — `BE`.
    ///
    /// ISO 3166-2: 3 regions, 10 provinces.
    Be,
    /// Burkina Faso — `BF`.
    ///
    /// ISO 3166-2: regions, 45 provinces.
    Bf,
    /// Bulgaria — `BG`.
    ///
    /// ISO 3166-2: 28 regions.
    Bg,
    /// Bahrain — `BH`.
    ///
    /// ISO 3166-2: 4 governorates.
    Bh,
    /// Burundi — `BI`.
    ///
    /// ISO 3166-2: 18 provinces.
    Bi,
    /// Benin — `BJ`.
    ///
    /// ISO 3166-2: 12 departments.
    Bj,
    /// Saint Barthélemy — `BL`.
    Bl,
    /// Bermuda — `BM`.
    Bm,
    /// Brunei Darussalam — `BN`.
    ///
    /// ISO 3166-2: districts.
    Bn,
    /// Bolivia, Plurinational State of — `BO`.
    ///
    /// ISO 3166-2: departments.
    Bo,
    /// Bonaire, Sint Eustatius and Saba — `BQ`.
    ///
    /// ISO 3166-2: special municipalities.
    Bq,
    /// Brazil — `BR`.
    ///
    /// ISO 3166-2: 1 federal district, 26 states.
    Br,
    /// Bahamas — `BS`.
    ///
    /// ISO 3166-2: 31 districts, 1 island.
    Bs,
    /// Bhutan — `BT`.
    ///
    /// ISO 3166-2: 20 districts.
    Bt,
    /// Bouvet Island — `BV`.
    Bv,
    /// Botswana — `BW`.
    ///
    /// ISO 3166-2: 10 districts, 4 towns, 2 cities.
    Bw,
    /// Belarus — `BY`.
    ///
    /// ISO 3166-2: 6 oblasts, 1 city.
    By,
    /// Belize — `BZ`.
    ///
    /// ISO 3166-2: 6 districts.
    Bz,
    /// Canada — `CA`.
    ///
    /// ISO 3166-2: 10 provinces, 3 territories.
    Ca,
    /// Cocos (Keeling) Islands — `CC`.
    Cc,
    /// Congo, Democratic Republic of the — `CD`.
    ///
    /// ISO 3166-2: 1 city, 25 provinces.
    Cd,
    /// Central African Republic — `CF`.
    ///
    /// ISO 3166-2: 1 commune, 14 prefectures, 2 economic prefectures.
    Cf,
    /// Congo — `CG`.
    ///
    /// ISO 3166-2: 12 departments.
    Cg,
    /// Switzerland — `CH`.
    ///
    /// ISO 3166-2: 26 cantons.
    Ch,
    /// Côte d'Ivoire — `CI`.
    ///
    /// ISO 3166-2: districts, 2 autonomous districts.
    Ci,
    /// Cook Islands — `CK`.
    Ck,
    /// Chile — `CL`.
    ///
    /// ISO 3166-2: 16 regions.
    Cl,
    /// Cameroon — `CM`.
    ///
    /// ISO 3166-2: 10 regions.
    Cm,
    /// China — `CN`.
    ///
    /// ISO 3166-2: 4 municipalities, 23 provinces, 5 autonomous regions, 2 special administrative regions.
    Cn,
    /// Colombia — `CO`.
    ///
    /// ISO 3166-2: 1 capital district, 32 departments.
    Co,
    /// Costa Rica — `CR`.
    ///
    /// ISO 3166-2: provinces.
    Cr,
    /// Cuba — `CU`.
    ///
    /// ISO 3166-2: 15 provinces, 1 special municipality.
    Cu,
    /// Cabo Verde — `CV`.
    ///
    /// ISO 3166-2: geographical regions, 22 municipalities.
    Cv,
    /// Curaçao — `CW`.
    Cw,
    /// Christmas Island — `CX`.
    Cx,
    /// Cyprus — `CY`.
    ///
    /// ISO 3166-2: 6 districts.
    Cy,
    /// Czechia — `CZ`.
    ///
    /// ISO 3166-2: 13 regions, 1 capital city, 76 districts.
    Cz,
    /// Germany — `DE`.
    ///
    /// ISO 3166-2: 16 states.
    De,
    /// Djibouti — `DJ`.
    ///
    /// ISO 3166-2: 5 regions, 1 city.
    Dj,
    /// Denmark — `DK`.
    ///
    /// ISO 3166-2: 5 regions.
    Dk,
    /// Dominica — `DM`.
    ///
    /// ISO 3166-2: 10 parishes.
    Dm,
    /// Dominican Republic — `DO`.
    ///
    /// ISO 3166-2: regions, 1 district, 31 provinces.
    Do,
    /// Algeria — `DZ`.
    ///
    /// ISO 3166-2: 58 provinces.
    Dz,
    /// Ecuador — `EC`.
    ///
    /// ISO 3166-2: 24 provinces.
    Ec,
    /// Estonia — `EE`.
    ///
    /// ISO 3166-2: 15 counties, 64 rural municipalities, 15 urban municipalities.
    Ee,
    /// Egypt — `EG`.
    ///
    /// ISO 3166-2: 27 governorates.
    Eg,
    /// Western Sahara — `EH`.
    Eh,
    /// Eritrea — `ER`.
    ///
    /// ISO 3166-2: 6 regions.
    Er,
    /// Spain — `ES`.
    ///
    /// ISO 3166-2: 17 autonomous communities, 2 autonomous cities in North Africa, 50 provinces.
    Es,
    /// Ethiopia — `ET`.
    ///
    /// ISO 3166-2: 2 administrations, 11 regional states.
    Et,
    /// Finland — `FI`.
    ///
    /// ISO 3166-2: 19 regions.
    Fi,
    /// Fiji — `FJ`.
    ///
    /// ISO 3166-2: 4 divisions, 1 dependency, 14 provinces.
    Fj,
    /// Falkland Islands (Malvinas) — `FK`.
    Fk,
    /// Micronesia, Federated States of — `FM`.
    ///
    /// ISO 3166-2: states.
    Fm,
    /// Faroe Islands — `FO`.
    Fo,
    /// France — `FR`.
    ///
    /// ISO 3166-2: 12 metropolitan regions and overseas collectivities/territories; 95 metropolitan departments and related entities.
    Fr,
    /// Gabon — `GA`.
    ///
    /// ISO 3166-2: 9 provinces.
    Ga,
    /// United Kingdom of Great Britain and Northern Ireland — `GB`.
    ///
    /// ISO 3166-2: countries, province, council areas, counties, districts, unitary authorities, metropolitan districts, London boroughs, city corporation.
    Gb,
    /// Grenada — `GD`.
    ///
    /// ISO 3166-2: 6 parishes, 1 dependency.
    Gd,
    /// Georgia — `GE`.
    ///
    /// ISO 3166-2: 2 autonomous republics, 1 city, 9 regions.
    Ge,
    /// French Guiana — `GF`.
    Gf,
    /// Guernsey — `GG`.
    Gg,
    /// Ghana — `GH`.
    ///
    /// ISO 3166-2: 16 regions.
    Gh,
    /// Gibraltar — `GI`.
    Gi,
    /// Greenland — `GL`.
    ///
    /// ISO 3166-2: 5 municipalities.
    Gl,
    /// Gambia — `GM`.
    ///
    /// ISO 3166-2: 1 city, 5 divisions.
    Gm,
    /// Guinea — `GN`.
    ///
    /// ISO 3166-2: 7 administrative regions, 1 governorate, 33 prefectures.
    Gn,
    /// Guadeloupe — `GP`.
    Gp,
    /// Equatorial Guinea — `GQ`.
    ///
    /// ISO 3166-2: regions, 8 provinces.
    Gq,
    /// Greece — `GR`.
    ///
    /// ISO 3166-2: 13 administrative regions, 1 self-governed part.
    Gr,
    /// South Georgia and the South Sandwich Islands — `GS`.
    Gs,
    /// Guatemala — `GT`.
    ///
    /// ISO 3166-2: 22 departments.
    Gt,
    /// Guam — `GU`.
    Gu,
    /// Guinea-Bissau — `GW`.
    ///
    /// ISO 3166-2: 3 provinces, 1 autonomous sector, 8 regions.
    Gw,
    /// Guyana — `GY`.
    ///
    /// ISO 3166-2: 10 regions.
    Gy,
    /// Hong Kong — `HK`.
    Hk,
    /// Heard Island and McDonald Islands — `HM`.
    Hm,
    /// Honduras — `HN`.
    ///
    /// ISO 3166-2: 18 departments.
    Hn,
    /// Croatia — `HR`.
    ///
    /// ISO 3166-2: 1 city, 20 counties.
    Hr,
    /// Haiti — `HT`.
    ///
    /// ISO 3166-2: 10 departments.
    Ht,
    /// Hungary — `HU`.
    ///
    /// ISO 3166-2: 1 capital city, 19 counties, 23 cities of county right.
    Hu,
    /// Indonesia — `ID`.
    ///
    /// ISO 3166-2: 7 geographical units, 36 provinces, 1 capital district, 1 special region.
    Id,
    /// Ireland — `IE`.
    ///
    /// ISO 3166-2: 4 provinces, 26 counties.
    Ie,
    /// Israel — `IL`.
    ///
    /// ISO 3166-2: 6 districts.
    Il,
    /// Isle of Man — `IM`.
    Im,
    /// India — `IN`.
    ///
    /// ISO 3166-2: 28 states, 8 union territories.
    In,
    /// British Indian Ocean Territory — `IO`.
    Io,
    /// Iraq — `IQ`.
    ///
    /// ISO 3166-2: 1 region, 18 governorates.
    Iq,
    /// Iran, Islamic Republic of — `IR`.
    ///
    /// ISO 3166-2: provinces.
    Ir,
    /// Iceland — `IS`.
    ///
    /// ISO 3166-2: 8 regions, 64 municipalities.
    Is,
    /// Italy — `IT`.
    ///
    /// ISO 3166-2: 15 regions, 5 autonomous regions, provinces, free municipal consortiums, metropolitan cities, decentralized regional entities.
    It,
    /// Jersey — `JE`.
    Je,
    /// Jamaica — `JM`.
    ///
    /// ISO 3166-2: 14 parishes.
    Jm,
    /// Jordan — `JO`.
    ///
    /// ISO 3166-2: 12 governorates.
    Jo,
    /// Japan — `JP`.
    ///
    /// ISO 3166-2: 47 prefectures.
    Jp,
    /// Kenya — `KE`.
    ///
    /// ISO 3166-2: 47 counties.
    Ke,
    /// Kyrgyzstan — `KG`.
    ///
    /// ISO 3166-2: 2 cities, 7 regions.
    Kg,
    /// Cambodia — `KH`.
    ///
    /// ISO 3166-2: 1 autonomous municipality, 24 provinces.
    Kh,
    /// Kiribati — `KI`.
    ///
    /// ISO 3166-2: 3 groups of islands.
    Ki,
    /// Comoros — `KM`.
    ///
    /// ISO 3166-2: 3 islands.
    Km,
    /// Saint Kitts and Nevis — `KN`.
    ///
    /// ISO 3166-2: states, 14 parishes.
    Kn,
    /// Korea, Democratic People's Republic of — `KP`.
    ///
    /// ISO 3166-2: capital city, metropolitan city, special city, 9 provinces.
    Kp,
    /// Korea, Republic of — `KR`.
    ///
    /// ISO 3166-2: metropolitan cities, special cities, special self-governing city, provinces, special self-governing provinces.
    Kr,
    /// Kuwait — `KW`.
    ///
    /// ISO 3166-2: 6 governorates.
    Kw,
    /// Cayman Islands — `KY`.
    Ky,
    /// Kazakhstan — `KZ`.
    ///
    /// ISO 3166-2: 3 cities, 17 regions.
    Kz,
    /// Lao People's Democratic Republic — `LA`.
    ///
    /// ISO 3166-2: 1 prefecture, 17 provinces.
    La,
    /// Lebanon — `LB`.
    ///
    /// ISO 3166-2: 8 governorates.
    Lb,
    /// Saint Lucia — `LC`.
    ///
    /// ISO 3166-2: districts.
    Lc,
    /// Liechtenstein — `LI`.
    ///
    /// ISO 3166-2: 11 communes.
    Li,
    /// Sri Lanka — `LK`.
    ///
    /// ISO 3166-2: provinces, 25 districts.
    Lk,
    /// Liberia — `LR`.
    ///
    /// ISO 3166-2: 15 counties.
    Lr,
    /// Lesotho — `LS`.
    ///
    /// ISO 3166-2: 10 districts.
    Ls,
    /// Lithuania — `LT`.
    ///
    /// ISO 3166-2: 10 counties, 9 municipalities, 7 city municipalities, 44 district municipalities.
    Lt,
    /// Luxembourg — `LU`.
    ///
    /// ISO 3166-2: 12 cantons.
    Lu,
    /// Latvia — `LV`.
    ///
    /// ISO 3166-2: 36 municipalities, 7 state cities.
    Lv,
    /// Libya — `LY`.
    ///
    /// ISO 3166-2: 22 popularates.
    Ly,
    /// Morocco — `MA`.
    ///
    /// ISO 3166-2: 12 regions, 62 provinces, 13 prefectures.
    Ma,
    /// Monaco — `MC`.
    ///
    /// ISO 3166-2: 17 quarters.
    Mc,
    /// Moldova, Republic of — `MD`.
    ///
    /// ISO 3166-2: autonomous territorial unit, 3 cities, 32 districts, 1 territorial unit.
    Md,
    /// Montenegro — `ME`.
    ///
    /// ISO 3166-2: 25 municipalities.
    Me,
    /// Saint Martin (French part) — `MF`.
    Mf,
    /// Madagascar — `MG`.
    ///
    /// ISO 3166-2: 6 provinces.
    Mg,
    /// Marshall Islands — `MH`.
    ///
    /// ISO 3166-2: chains of islands, 24 municipalities.
    Mh,
    /// North Macedonia — `MK`.
    ///
    /// ISO 3166-2: municipalities.
    Mk,
    /// Mali — `ML`.
    ///
    /// ISO 3166-2: 1 district, 10 regions.
    Ml,
    /// Myanmar — `MM`.
    ///
    /// ISO 3166-2: 7 regions, 7 states, 1 union territory.
    Mm,
    /// Mongolia — `MN`.
    ///
    /// ISO 3166-2: 1 capital city, 21 provinces.
    Mn,
    /// Macao — `MO`.
    Mo,
    /// Northern Mariana Islands — `MP`.
    Mp,
    /// Martinique — `MQ`.
    Mq,
    /// Mauritania — `MR`.
    ///
    /// ISO 3166-2: 15 regions.
    Mr,
    /// Montserrat — `MS`.
    Ms,
    /// Malta — `MT`.
    ///
    /// ISO 3166-2: 68 local councils.
    Mt,
    /// Mauritius — `MU`.
    ///
    /// ISO 3166-2: 3 dependencies, 9 districts.
    Mu,
    /// Maldives — `MV`.
    ///
    /// ISO 3166-2: 19 administrative atolls, 2 cities.
    Mv,
    /// Malawi — `MW`.
    ///
    /// ISO 3166-2: 3 regions, 28 districts.
    Mw,
    /// Mexico — `MX`.
    ///
    /// ISO 3166-2: 31 states, 1 federal entity.
    Mx,
    /// Malaysia — `MY`.
    ///
    /// ISO 3166-2: 3 federal territories, 13 states.
    My,
    /// Mozambique — `MZ`.
    ///
    /// ISO 3166-2: 1 city, 10 provinces.
    Mz,
    /// Namibia — `NA`.
    ///
    /// ISO 3166-2: 14 regions.
    Na,
    /// New Caledonia — `NC`.
    Nc,
    /// Niger — `NE`.
    ///
    /// ISO 3166-2: 1 urban community, 7 departments.
    Ne,
    /// Norfolk Island — `NF`.
    Nf,
    /// Nigeria — `NG`.
    ///
    /// ISO 3166-2: 1 capital territory, 36 states.
    Ng,
    /// Nicaragua — `NI`.
    ///
    /// ISO 3166-2: 15 departments, 2 autonomous regions.
    Ni,
    /// Netherlands, Kingdom of the — `NL`.
    ///
    /// ISO 3166-2: provinces, 3 countries, 3 special municipalities.
    Nl,
    /// Norway — `NO`.
    ///
    /// ISO 3166-2: 11 counties, 2 arctic regions.
    No,
    /// Nepal — `NP`.
    ///
    /// ISO 3166-2: 7 provinces.
    Np,
    /// Nauru — `NR`.
    ///
    /// ISO 3166-2: 14 districts.
    Nr,
    /// Niue — `NU`.
    Nu,
    /// New Zealand — `NZ`.
    ///
    /// ISO 3166-2: regions, 1 special island authority.
    Nz,
    /// Oman — `OM`.
    ///
    /// ISO 3166-2: 11 governorates.
    Om,
    /// Panama — `PA`.
    ///
    /// ISO 3166-2: 10 provinces, 4 indigenous regions.
    Pa,
    /// Peru — `PE`.
    ///
    /// ISO 3166-2: 25 regions, 1 municipality.
    Pe,
    /// French Polynesia — `PF`.
    Pf,
    /// Papua New Guinea — `PG`.
    ///
    /// ISO 3166-2: 1 district, 20 provinces, 1 autonomous region.
    Pg,
    /// Philippines — `PH`.
    ///
    /// ISO 3166-2: 17 regions, 82 provinces.
    Ph,
    /// Pakistan — `PK`.
    ///
    /// ISO 3166-2: 4 provinces, 2 autonomous territories, 1 federal territory.
    Pk,
    /// Poland — `PL`.
    ///
    /// ISO 3166-2: 16 voivodships.
    Pl,
    /// Saint Pierre and Miquelon — `PM`.
    Pm,
    /// Pitcairn — `PN`.
    Pn,
    /// Puerto Rico — `PR`.
    Pr,
    /// Palestine, State of — `PS`.
    ///
    /// ISO 3166-2: governorates.
    Ps,
    /// Portugal — `PT`.
    ///
    /// ISO 3166-2: 18 districts, 2 autonomous regions.
    Pt,
    /// Palau — `PW`.
    ///
    /// ISO 3166-2: 16 states.
    Pw,
    /// Paraguay — `PY`.
    ///
    /// ISO 3166-2: 1 capital, 17 departments.
    Py,
    /// Qatar — `QA`.
    ///
    /// ISO 3166-2: 8 municipalities.
    Qa,
    /// Réunion — `RE`.
    Re,
    /// Romania — `RO`.
    ///
    /// ISO 3166-2: 41 departments, 1 municipality.
    Ro,
    /// Serbia — `RS`.
    ///
    /// ISO 3166-2: 2 autonomous provinces, 1 city, 29 districts.
    Rs,
    /// Russian Federation — `RU`.
    ///
    /// ISO 3166-2: republics, administrative territories, administrative regions, autonomous cities, autonomous region, autonomous districts.
    Ru,
    /// Rwanda — `RW`.
    ///
    /// ISO 3166-2: 1 town council, 4 provinces.
    Rw,
    /// Saudi Arabia — `SA`.
    ///
    /// ISO 3166-2: regions.
    Sa,
    /// Solomon Islands — `SB`.
    ///
    /// ISO 3166-2: 1 capital territory, 9 provinces.
    Sb,
    /// Seychelles — `SC`.
    ///
    /// ISO 3166-2: 27 districts.
    Sc,
    /// Sudan — `SD`.
    ///
    /// ISO 3166-2: 18 states.
    Sd,
    /// Sweden — `SE`.
    ///
    /// ISO 3166-2: 21 counties.
    Se,
    /// Singapore — `SG`.
    ///
    /// ISO 3166-2: 5 districts.
    Sg,
    /// Saint Helena, Ascension and Tristan da Cunha — `SH`.
    ///
    /// ISO 3166-2: geographical entities.
    Sh,
    /// Slovenia — `SI`.
    ///
    /// ISO 3166-2: 200 municipalities and 12 urban municipalities.
    Si,
    /// Svalbard and Jan Mayen — `SJ`.
    Sj,
    /// Slovakia — `SK`.
    ///
    /// ISO 3166-2: 8 regions.
    Sk,
    /// Sierra Leone — `SL`.
    ///
    /// ISO 3166-2: area, 4 provinces.
    Sl,
    /// San Marino — `SM`.
    ///
    /// ISO 3166-2: municipalities.
    Sm,
    /// Senegal — `SN`.
    ///
    /// ISO 3166-2: 14 regions.
    Sn,
    /// Somalia — `SO`.
    ///
    /// ISO 3166-2: 18 regions.
    So,
    /// Suriname — `SR`.
    ///
    /// ISO 3166-2: 10 districts.
    Sr,
    /// South Sudan — `SS`.
    ///
    /// ISO 3166-2: states.
    Ss,
    /// Sao Tome and Principe — `ST`.
    ///
    /// ISO 3166-2: 1 autonomous region, 6 districts.
    St,
    /// El Salvador — `SV`.
    ///
    /// ISO 3166-2: departments.
    Sv,
    /// Sint Maarten (Dutch part) — `SX`.
    Sx,
    /// Syrian Arab Republic — `SY`.
    ///
    /// ISO 3166-2: provinces.
    Sy,
    /// Eswatini — `SZ`.
    ///
    /// ISO 3166-2: 4 regions.
    Sz,
    /// Turks and Caicos Islands — `TC`.
    Tc,
    /// Chad — `TD`.
    ///
    /// ISO 3166-2: 23 provinces.
    Td,
    /// French Southern Territories — `TF`.
    Tf,
    /// Togo — `TG`.
    ///
    /// ISO 3166-2: 5 regions.
    Tg,
    /// Thailand — `TH`.
    ///
    /// ISO 3166-2: 1 metropolitan administration, 1 special administrative city, 76 provinces.
    Th,
    /// Tajikistan — `TJ`.
    ///
    /// ISO 3166-2: 1 autonomous region, 2 regions, 1 capital territory, 1 district under republic administration.
    Tj,
    /// Tokelau — `TK`.
    Tk,
    /// Timor-Leste — `TL`.
    ///
    /// ISO 3166-2: 12 municipalities, 1 special administrative region.
    Tl,
    /// Turkmenistan — `TM`.
    ///
    /// ISO 3166-2: 5 regions, 1 city.
    Tm,
    /// Tunisia — `TN`.
    ///
    /// ISO 3166-2: 24 governorates.
    Tn,
    /// Tonga — `TO`.
    ///
    /// ISO 3166-2: 5 divisions.
    To,
    /// Türkiye — `TR`.
    ///
    /// ISO 3166-2: 81 provinces.
    Tr,
    /// Trinidad and Tobago — `TT`.
    ///
    /// ISO 3166-2: regions, 3 boroughs, 2 cities, 1 ward.
    Tt,
    /// Tuvalu — `TV`.
    ///
    /// ISO 3166-2: 1 town council, 7 island councils.
    Tv,
    /// Taiwan, Province of China — `TW`.
    ///
    /// ISO 3166-2: counties, 3 cities, 6 special municipalities.
    Tw,
    /// Tanzania, United Republic of — `TZ`.
    ///
    /// ISO 3166-2: regions.
    Tz,
    /// Ukraine — `UA`.
    ///
    /// ISO 3166-2: 24 regions, 1 republic, 2 cities.
    Ua,
    /// Uganda — `UG`.
    ///
    /// ISO 3166-2: 4 geographical regions, 134 districts, 1 city.
    Ug,
    /// United States Minor Outlying Islands — `UM`.
    ///
    /// ISO 3166-2: islands, groups of islands.
    Um,
    /// United States of America — `US`.
    ///
    /// ISO 3166-2: states, 1 district, 6 outlying areas.
    Us,
    /// Uruguay — `UY`.
    ///
    /// ISO 3166-2: 19 departments.
    Uy,
    /// Uzbekistan — `UZ`.
    ///
    /// ISO 3166-2: 1 city, 12 regions, 1 republic.
    Uz,
    /// Holy See — `VA`.
    Va,
    /// Saint Vincent and the Grenadines — `VC`.
    ///
    /// ISO 3166-2: parishes.
    Vc,
    /// Venezuela, Bolivarian Republic of — `VE`.
    ///
    /// ISO 3166-2: federal dependency, 1 federal district, 23 states.
    Ve,
    /// Virgin Islands (British) — `VG`.
    Vg,
    /// Virgin Islands (U.S.) — `VI`.
    Vi,
    /// Viet Nam — `VN`.
    ///
    /// ISO 3166-2: provinces, 5 municipalities.
    Vn,
    /// Vanuatu — `VU`.
    ///
    /// ISO 3166-2: 6 provinces.
    Vu,
    /// Wallis and Futuna — `WF`.
    ///
    /// ISO 3166-2: administrative precincts.
    Wf,
    /// Samoa — `WS`.
    ///
    /// ISO 3166-2: 11 districts.
    Ws,
    /// Yemen — `YE`.
    ///
    /// ISO 3166-2: 1 municipality, 21 governorates.
    Ye,
    /// Mayotte — `YT`.
    Yt,
    /// South Africa — `ZA`.
    ///
    /// ISO 3166-2: provinces.
    Za,
    /// Zambia — `ZM`.
    ///
    /// ISO 3166-2: 10 provinces.
    Zm,
    /// Zimbabwe — `ZW`.
    ///
    /// ISO 3166-2: 10 provinces.
    Zw,
}

impl CountryCode {
    /// Andorra.
    pub const AD: Self = Self::Ad;
    /// United Arab Emirates.
    pub const AE: Self = Self::Ae;
    /// Afghanistan.
    pub const AF: Self = Self::Af;
    /// Antigua and Barbuda.
    pub const AG: Self = Self::Ag;
    /// Anguilla.
    pub const AI: Self = Self::Ai;
    /// Albania.
    pub const AL: Self = Self::Al;
    /// Armenia.
    pub const AM: Self = Self::Am;
    /// Netherlands Antilles (historically assigned; transitional ISO code).
    pub const AN: Self = Self::An;
    /// Angola.
    pub const AO: Self = Self::Ao;
    /// Antarctica.
    pub const AQ: Self = Self::Aq;
    /// Argentina.
    pub const AR: Self = Self::Ar;
    /// American Samoa.
    pub const AS: Self = Self::As;
    /// Austria.
    pub const AT: Self = Self::At;
    /// Australia.
    pub const AU: Self = Self::Au;
    /// Aruba.
    pub const AW: Self = Self::Aw;
    /// Åland Islands.
    pub const AX: Self = Self::Ax;
    /// Azerbaijan.
    pub const AZ: Self = Self::Az;
    /// Bosnia and Herzegovina.
    pub const BA: Self = Self::Ba;
    /// Barbados.
    pub const BB: Self = Self::Bb;
    /// Bangladesh.
    pub const BD: Self = Self::Bd;
    /// Belgium.
    pub const BE: Self = Self::Be;
    /// Burkina Faso.
    pub const BF: Self = Self::Bf;
    /// Bulgaria.
    pub const BG: Self = Self::Bg;
    /// Bahrain.
    pub const BH: Self = Self::Bh;
    /// Burundi.
    pub const BI: Self = Self::Bi;
    /// Benin.
    pub const BJ: Self = Self::Bj;
    /// Saint Barthélemy.
    pub const BL: Self = Self::Bl;
    /// Bermuda.
    pub const BM: Self = Self::Bm;
    /// Brunei Darussalam.
    pub const BN: Self = Self::Bn;
    /// Bolivia, Plurinational State of.
    pub const BO: Self = Self::Bo;
    /// Bonaire, Sint Eustatius and Saba.
    pub const BQ: Self = Self::Bq;
    /// Brazil.
    pub const BR: Self = Self::Br;
    /// Bahamas.
    pub const BS: Self = Self::Bs;
    /// Bhutan.
    pub const BT: Self = Self::Bt;
    /// Bouvet Island.
    pub const BV: Self = Self::Bv;
    /// Botswana.
    pub const BW: Self = Self::Bw;
    /// Belarus.
    pub const BY: Self = Self::By;
    /// Belize.
    pub const BZ: Self = Self::Bz;
    /// Canada.
    pub const CA: Self = Self::Ca;
    /// Cocos (Keeling) Islands.
    pub const CC: Self = Self::Cc;
    /// Congo, Democratic Republic of the.
    pub const CD: Self = Self::Cd;
    /// Central African Republic.
    pub const CF: Self = Self::Cf;
    /// Congo.
    pub const CG: Self = Self::Cg;
    /// Switzerland.
    pub const CH: Self = Self::Ch;
    /// Côte d'Ivoire.
    pub const CI: Self = Self::Ci;
    /// Cook Islands.
    pub const CK: Self = Self::Ck;
    /// Chile.
    pub const CL: Self = Self::Cl;
    /// Cameroon.
    pub const CM: Self = Self::Cm;
    /// China.
    pub const CN: Self = Self::Cn;
    /// Colombia.
    pub const CO: Self = Self::Co;
    /// Costa Rica.
    pub const CR: Self = Self::Cr;
    /// Cuba.
    pub const CU: Self = Self::Cu;
    /// Cabo Verde.
    pub const CV: Self = Self::Cv;
    /// Curaçao.
    pub const CW: Self = Self::Cw;
    /// Christmas Island.
    pub const CX: Self = Self::Cx;
    /// Cyprus.
    pub const CY: Self = Self::Cy;
    /// Czechia.
    pub const CZ: Self = Self::Cz;
    /// Germany.
    pub const DE: Self = Self::De;
    /// Djibouti.
    pub const DJ: Self = Self::Dj;
    /// Denmark.
    pub const DK: Self = Self::Dk;
    /// Dominica.
    pub const DM: Self = Self::Dm;
    /// Dominican Republic.
    pub const DO: Self = Self::Do;
    /// Algeria.
    pub const DZ: Self = Self::Dz;
    /// Ecuador.
    pub const EC: Self = Self::Ec;
    /// Estonia.
    pub const EE: Self = Self::Ee;
    /// Egypt.
    pub const EG: Self = Self::Eg;
    /// Western Sahara.
    pub const EH: Self = Self::Eh;
    /// Eritrea.
    pub const ER: Self = Self::Er;
    /// Spain.
    pub const ES: Self = Self::Es;
    /// Ethiopia.
    pub const ET: Self = Self::Et;
    /// Finland.
    pub const FI: Self = Self::Fi;
    /// Fiji.
    pub const FJ: Self = Self::Fj;
    /// Falkland Islands (Malvinas).
    pub const FK: Self = Self::Fk;
    /// Micronesia, Federated States of.
    pub const FM: Self = Self::Fm;
    /// Faroe Islands.
    pub const FO: Self = Self::Fo;
    /// France.
    pub const FR: Self = Self::Fr;
    /// Gabon.
    pub const GA: Self = Self::Ga;
    /// United Kingdom of Great Britain and Northern Ireland.
    pub const GB: Self = Self::Gb;
    /// Grenada.
    pub const GD: Self = Self::Gd;
    /// Georgia.
    pub const GE: Self = Self::Ge;
    /// French Guiana.
    pub const GF: Self = Self::Gf;
    /// Guernsey.
    pub const GG: Self = Self::Gg;
    /// Ghana.
    pub const GH: Self = Self::Gh;
    /// Gibraltar.
    pub const GI: Self = Self::Gi;
    /// Greenland.
    pub const GL: Self = Self::Gl;
    /// Gambia.
    pub const GM: Self = Self::Gm;
    /// Guinea.
    pub const GN: Self = Self::Gn;
    /// Guadeloupe.
    pub const GP: Self = Self::Gp;
    /// Equatorial Guinea.
    pub const GQ: Self = Self::Gq;
    /// Greece.
    pub const GR: Self = Self::Gr;
    /// South Georgia and the South Sandwich Islands.
    pub const GS: Self = Self::Gs;
    /// Guatemala.
    pub const GT: Self = Self::Gt;
    /// Guam.
    pub const GU: Self = Self::Gu;
    /// Guinea-Bissau.
    pub const GW: Self = Self::Gw;
    /// Guyana.
    pub const GY: Self = Self::Gy;
    /// Hong Kong.
    pub const HK: Self = Self::Hk;
    /// Heard Island and McDonald Islands.
    pub const HM: Self = Self::Hm;
    /// Honduras.
    pub const HN: Self = Self::Hn;
    /// Croatia.
    pub const HR: Self = Self::Hr;
    /// Haiti.
    pub const HT: Self = Self::Ht;
    /// Hungary.
    pub const HU: Self = Self::Hu;
    /// Indonesia.
    pub const ID: Self = Self::Id;
    /// Ireland.
    pub const IE: Self = Self::Ie;
    /// Israel.
    pub const IL: Self = Self::Il;
    /// Isle of Man.
    pub const IM: Self = Self::Im;
    /// India.
    pub const IN: Self = Self::In;
    /// British Indian Ocean Territory.
    pub const IO: Self = Self::Io;
    /// Iraq.
    pub const IQ: Self = Self::Iq;
    /// Iran, Islamic Republic of.
    pub const IR: Self = Self::Ir;
    /// Iceland.
    pub const IS: Self = Self::Is;
    /// Italy.
    pub const IT: Self = Self::It;
    /// Jersey.
    pub const JE: Self = Self::Je;
    /// Jamaica.
    pub const JM: Self = Self::Jm;
    /// Jordan.
    pub const JO: Self = Self::Jo;
    /// Japan.
    pub const JP: Self = Self::Jp;
    /// Kenya.
    pub const KE: Self = Self::Ke;
    /// Kyrgyzstan.
    pub const KG: Self = Self::Kg;
    /// Cambodia.
    pub const KH: Self = Self::Kh;
    /// Kiribati.
    pub const KI: Self = Self::Ki;
    /// Comoros.
    pub const KM: Self = Self::Km;
    /// Saint Kitts and Nevis.
    pub const KN: Self = Self::Kn;
    /// Korea, Democratic People's Republic of.
    pub const KP: Self = Self::Kp;
    /// Korea, Republic of.
    pub const KR: Self = Self::Kr;
    /// Kuwait.
    pub const KW: Self = Self::Kw;
    /// Cayman Islands.
    pub const KY: Self = Self::Ky;
    /// Kazakhstan.
    pub const KZ: Self = Self::Kz;
    /// Lao People's Democratic Republic.
    pub const LA: Self = Self::La;
    /// Lebanon.
    pub const LB: Self = Self::Lb;
    /// Saint Lucia.
    pub const LC: Self = Self::Lc;
    /// Liechtenstein.
    pub const LI: Self = Self::Li;
    /// Sri Lanka.
    pub const LK: Self = Self::Lk;
    /// Liberia.
    pub const LR: Self = Self::Lr;
    /// Lesotho.
    pub const LS: Self = Self::Ls;
    /// Lithuania.
    pub const LT: Self = Self::Lt;
    /// Luxembourg.
    pub const LU: Self = Self::Lu;
    /// Latvia.
    pub const LV: Self = Self::Lv;
    /// Libya.
    pub const LY: Self = Self::Ly;
    /// Morocco.
    pub const MA: Self = Self::Ma;
    /// Monaco.
    pub const MC: Self = Self::Mc;
    /// Moldova, Republic of.
    pub const MD: Self = Self::Md;
    /// Montenegro.
    pub const ME: Self = Self::Me;
    /// Saint Martin (French part).
    pub const MF: Self = Self::Mf;
    /// Madagascar.
    pub const MG: Self = Self::Mg;
    /// Marshall Islands.
    pub const MH: Self = Self::Mh;
    /// North Macedonia.
    pub const MK: Self = Self::Mk;
    /// Mali.
    pub const ML: Self = Self::Ml;
    /// Myanmar.
    pub const MM: Self = Self::Mm;
    /// Mongolia.
    pub const MN: Self = Self::Mn;
    /// Macao.
    pub const MO: Self = Self::Mo;
    /// Northern Mariana Islands.
    pub const MP: Self = Self::Mp;
    /// Martinique.
    pub const MQ: Self = Self::Mq;
    /// Mauritania.
    pub const MR: Self = Self::Mr;
    /// Montserrat.
    pub const MS: Self = Self::Ms;
    /// Malta.
    pub const MT: Self = Self::Mt;
    /// Mauritius.
    pub const MU: Self = Self::Mu;
    /// Maldives.
    pub const MV: Self = Self::Mv;
    /// Malawi.
    pub const MW: Self = Self::Mw;
    /// Mexico.
    pub const MX: Self = Self::Mx;
    /// Malaysia.
    pub const MY: Self = Self::My;
    /// Mozambique.
    pub const MZ: Self = Self::Mz;
    /// Namibia.
    pub const NA: Self = Self::Na;
    /// New Caledonia.
    pub const NC: Self = Self::Nc;
    /// Niger.
    pub const NE: Self = Self::Ne;
    /// Norfolk Island.
    pub const NF: Self = Self::Nf;
    /// Nigeria.
    pub const NG: Self = Self::Ng;
    /// Nicaragua.
    pub const NI: Self = Self::Ni;
    /// Netherlands, Kingdom of the.
    pub const NL: Self = Self::Nl;
    /// Norway.
    pub const NO: Self = Self::No;
    /// Nepal.
    pub const NP: Self = Self::Np;
    /// Nauru.
    pub const NR: Self = Self::Nr;
    /// Niue.
    pub const NU: Self = Self::Nu;
    /// New Zealand.
    pub const NZ: Self = Self::Nz;
    /// Oman.
    pub const OM: Self = Self::Om;
    /// Panama.
    pub const PA: Self = Self::Pa;
    /// Peru.
    pub const PE: Self = Self::Pe;
    /// French Polynesia.
    pub const PF: Self = Self::Pf;
    /// Papua New Guinea.
    pub const PG: Self = Self::Pg;
    /// Philippines.
    pub const PH: Self = Self::Ph;
    /// Pakistan.
    pub const PK: Self = Self::Pk;
    /// Poland.
    pub const PL: Self = Self::Pl;
    /// Saint Pierre and Miquelon.
    pub const PM: Self = Self::Pm;
    /// Pitcairn.
    pub const PN: Self = Self::Pn;
    /// Puerto Rico.
    pub const PR: Self = Self::Pr;
    /// Palestine, State of.
    pub const PS: Self = Self::Ps;
    /// Portugal.
    pub const PT: Self = Self::Pt;
    /// Palau.
    pub const PW: Self = Self::Pw;
    /// Paraguay.
    pub const PY: Self = Self::Py;
    /// Qatar.
    pub const QA: Self = Self::Qa;
    /// Réunion.
    pub const RE: Self = Self::Re;
    /// Romania.
    pub const RO: Self = Self::Ro;
    /// Serbia.
    pub const RS: Self = Self::Rs;
    /// Russian Federation.
    pub const RU: Self = Self::Ru;
    /// Rwanda.
    pub const RW: Self = Self::Rw;
    /// Saudi Arabia.
    pub const SA: Self = Self::Sa;
    /// Solomon Islands.
    pub const SB: Self = Self::Sb;
    /// Seychelles.
    pub const SC: Self = Self::Sc;
    /// Sudan.
    pub const SD: Self = Self::Sd;
    /// Sweden.
    pub const SE: Self = Self::Se;
    /// Singapore.
    pub const SG: Self = Self::Sg;
    /// Saint Helena, Ascension and Tristan da Cunha.
    pub const SH: Self = Self::Sh;
    /// Slovenia.
    pub const SI: Self = Self::Si;
    /// Svalbard and Jan Mayen.
    pub const SJ: Self = Self::Sj;
    /// Slovakia.
    pub const SK: Self = Self::Sk;
    /// Sierra Leone.
    pub const SL: Self = Self::Sl;
    /// San Marino.
    pub const SM: Self = Self::Sm;
    /// Senegal.
    pub const SN: Self = Self::Sn;
    /// Somalia.
    pub const SO: Self = Self::So;
    /// Suriname.
    pub const SR: Self = Self::Sr;
    /// South Sudan.
    pub const SS: Self = Self::Ss;
    /// Sao Tome and Principe.
    pub const ST: Self = Self::St;
    /// El Salvador.
    pub const SV: Self = Self::Sv;
    /// Sint Maarten (Dutch part).
    pub const SX: Self = Self::Sx;
    /// Syrian Arab Republic.
    pub const SY: Self = Self::Sy;
    /// Eswatini.
    pub const SZ: Self = Self::Sz;
    /// Turks and Caicos Islands.
    pub const TC: Self = Self::Tc;
    /// Chad.
    pub const TD: Self = Self::Td;
    /// French Southern Territories.
    pub const TF: Self = Self::Tf;
    /// Togo.
    pub const TG: Self = Self::Tg;
    /// Thailand.
    pub const TH: Self = Self::Th;
    /// Tajikistan.
    pub const TJ: Self = Self::Tj;
    /// Tokelau.
    pub const TK: Self = Self::Tk;
    /// Timor-Leste.
    pub const TL: Self = Self::Tl;
    /// Turkmenistan.
    pub const TM: Self = Self::Tm;
    /// Tunisia.
    pub const TN: Self = Self::Tn;
    /// Tonga.
    pub const TO: Self = Self::To;
    /// Türkiye.
    pub const TR: Self = Self::Tr;
    /// Trinidad and Tobago.
    pub const TT: Self = Self::Tt;
    /// Tuvalu.
    pub const TV: Self = Self::Tv;
    /// Taiwan, Province of China.
    pub const TW: Self = Self::Tw;
    /// Tanzania, United Republic of.
    pub const TZ: Self = Self::Tz;
    /// Ukraine.
    pub const UA: Self = Self::Ua;
    /// Uganda.
    pub const UG: Self = Self::Ug;
    /// United States Minor Outlying Islands.
    pub const UM: Self = Self::Um;
    /// United States of America.
    pub const US: Self = Self::Us;
    /// Uruguay.
    pub const UY: Self = Self::Uy;
    /// Uzbekistan.
    pub const UZ: Self = Self::Uz;
    /// Holy See.
    pub const VA: Self = Self::Va;
    /// Saint Vincent and the Grenadines.
    pub const VC: Self = Self::Vc;
    /// Venezuela, Bolivarian Republic of.
    pub const VE: Self = Self::Ve;
    /// Virgin Islands (British).
    pub const VG: Self = Self::Vg;
    /// Virgin Islands (U.S.).
    pub const VI: Self = Self::Vi;
    /// Viet Nam.
    pub const VN: Self = Self::Vn;
    /// Vanuatu.
    pub const VU: Self = Self::Vu;
    /// Wallis and Futuna.
    pub const WF: Self = Self::Wf;
    /// Samoa.
    pub const WS: Self = Self::Ws;
    /// Yemen.
    pub const YE: Self = Self::Ye;
    /// Mayotte.
    pub const YT: Self = Self::Yt;
    /// South Africa.
    pub const ZA: Self = Self::Za;
    /// Zambia.
    pub const ZM: Self = Self::Zm;
    /// Zimbabwe.
    pub const ZW: Self = Self::Zw;

    /// All ISO 3166-1 alpha-2 codes recognized by this crate (250).
    pub const ALL: [Self; 250] = [
        Self::Ad,
        Self::Ae,
        Self::Af,
        Self::Ag,
        Self::Ai,
        Self::Al,
        Self::Am,
        Self::An,
        Self::Ao,
        Self::Aq,
        Self::Ar,
        Self::As,
        Self::At,
        Self::Au,
        Self::Aw,
        Self::Ax,
        Self::Az,
        Self::Ba,
        Self::Bb,
        Self::Bd,
        Self::Be,
        Self::Bf,
        Self::Bg,
        Self::Bh,
        Self::Bi,
        Self::Bj,
        Self::Bl,
        Self::Bm,
        Self::Bn,
        Self::Bo,
        Self::Bq,
        Self::Br,
        Self::Bs,
        Self::Bt,
        Self::Bv,
        Self::Bw,
        Self::By,
        Self::Bz,
        Self::Ca,
        Self::Cc,
        Self::Cd,
        Self::Cf,
        Self::Cg,
        Self::Ch,
        Self::Ci,
        Self::Ck,
        Self::Cl,
        Self::Cm,
        Self::Cn,
        Self::Co,
        Self::Cr,
        Self::Cu,
        Self::Cv,
        Self::Cw,
        Self::Cx,
        Self::Cy,
        Self::Cz,
        Self::De,
        Self::Dj,
        Self::Dk,
        Self::Dm,
        Self::Do,
        Self::Dz,
        Self::Ec,
        Self::Ee,
        Self::Eg,
        Self::Eh,
        Self::Er,
        Self::Es,
        Self::Et,
        Self::Fi,
        Self::Fj,
        Self::Fk,
        Self::Fm,
        Self::Fo,
        Self::Fr,
        Self::Ga,
        Self::Gb,
        Self::Gd,
        Self::Ge,
        Self::Gf,
        Self::Gg,
        Self::Gh,
        Self::Gi,
        Self::Gl,
        Self::Gm,
        Self::Gn,
        Self::Gp,
        Self::Gq,
        Self::Gr,
        Self::Gs,
        Self::Gt,
        Self::Gu,
        Self::Gw,
        Self::Gy,
        Self::Hk,
        Self::Hm,
        Self::Hn,
        Self::Hr,
        Self::Ht,
        Self::Hu,
        Self::Id,
        Self::Ie,
        Self::Il,
        Self::Im,
        Self::In,
        Self::Io,
        Self::Iq,
        Self::Ir,
        Self::Is,
        Self::It,
        Self::Je,
        Self::Jm,
        Self::Jo,
        Self::Jp,
        Self::Ke,
        Self::Kg,
        Self::Kh,
        Self::Ki,
        Self::Km,
        Self::Kn,
        Self::Kp,
        Self::Kr,
        Self::Kw,
        Self::Ky,
        Self::Kz,
        Self::La,
        Self::Lb,
        Self::Lc,
        Self::Li,
        Self::Lk,
        Self::Lr,
        Self::Ls,
        Self::Lt,
        Self::Lu,
        Self::Lv,
        Self::Ly,
        Self::Ma,
        Self::Mc,
        Self::Md,
        Self::Me,
        Self::Mf,
        Self::Mg,
        Self::Mh,
        Self::Mk,
        Self::Ml,
        Self::Mm,
        Self::Mn,
        Self::Mo,
        Self::Mp,
        Self::Mq,
        Self::Mr,
        Self::Ms,
        Self::Mt,
        Self::Mu,
        Self::Mv,
        Self::Mw,
        Self::Mx,
        Self::My,
        Self::Mz,
        Self::Na,
        Self::Nc,
        Self::Ne,
        Self::Nf,
        Self::Ng,
        Self::Ni,
        Self::Nl,
        Self::No,
        Self::Np,
        Self::Nr,
        Self::Nu,
        Self::Nz,
        Self::Om,
        Self::Pa,
        Self::Pe,
        Self::Pf,
        Self::Pg,
        Self::Ph,
        Self::Pk,
        Self::Pl,
        Self::Pm,
        Self::Pn,
        Self::Pr,
        Self::Ps,
        Self::Pt,
        Self::Pw,
        Self::Py,
        Self::Qa,
        Self::Re,
        Self::Ro,
        Self::Rs,
        Self::Ru,
        Self::Rw,
        Self::Sa,
        Self::Sb,
        Self::Sc,
        Self::Sd,
        Self::Se,
        Self::Sg,
        Self::Sh,
        Self::Si,
        Self::Sj,
        Self::Sk,
        Self::Sl,
        Self::Sm,
        Self::Sn,
        Self::So,
        Self::Sr,
        Self::Ss,
        Self::St,
        Self::Sv,
        Self::Sx,
        Self::Sy,
        Self::Sz,
        Self::Tc,
        Self::Td,
        Self::Tf,
        Self::Tg,
        Self::Th,
        Self::Tj,
        Self::Tk,
        Self::Tl,
        Self::Tm,
        Self::Tn,
        Self::To,
        Self::Tr,
        Self::Tt,
        Self::Tv,
        Self::Tw,
        Self::Tz,
        Self::Ua,
        Self::Ug,
        Self::Um,
        Self::Us,
        Self::Uy,
        Self::Uz,
        Self::Va,
        Self::Vc,
        Self::Ve,
        Self::Vg,
        Self::Vi,
        Self::Vn,
        Self::Vu,
        Self::Wf,
        Self::Ws,
        Self::Ye,
        Self::Yt,
        Self::Za,
        Self::Zm,
        Self::Zw,
    ];

    /// Parses an ISO 3166-1 alpha-2 country code.
    ///
    /// Accepts the uppercase wire form only (`NL`, not `nl` or `NLD`).
    ///
    /// # Errors
    ///
    /// Returns [`MollieError::InvalidRequest`] when the value is not a
    /// recognized two-letter uppercase code.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use mollie_rs::CountryCode;
    ///
    /// assert_eq!(CountryCode::parse("NL")?, CountryCode::NL);
    /// assert_eq!(CountryCode::NL.name(), "Netherlands, Kingdom of the");
    /// assert!(CountryCode::parse("nl").is_err());
    /// assert!(CountryCode::parse("NLD").is_err());
    /// # Ok::<(), mollie_rs::MollieError>(())
    /// ```
    pub fn parse(value: impl AsRef<str>) -> MollieResult<Self> {
        value.as_ref().parse()
    }

    /// Returns the uppercase ISO 3166-1 alpha-2 **entry** code.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use mollie_rs::CountryCode;
    ///
    /// assert_eq!(CountryCode::NL.as_str(), "NL");
    /// ```
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ad => "AD",
            Self::Ae => "AE",
            Self::Af => "AF",
            Self::Ag => "AG",
            Self::Ai => "AI",
            Self::Al => "AL",
            Self::Am => "AM",
            Self::An => "AN",
            Self::Ao => "AO",
            Self::Aq => "AQ",
            Self::Ar => "AR",
            Self::As => "AS",
            Self::At => "AT",
            Self::Au => "AU",
            Self::Aw => "AW",
            Self::Ax => "AX",
            Self::Az => "AZ",
            Self::Ba => "BA",
            Self::Bb => "BB",
            Self::Bd => "BD",
            Self::Be => "BE",
            Self::Bf => "BF",
            Self::Bg => "BG",
            Self::Bh => "BH",
            Self::Bi => "BI",
            Self::Bj => "BJ",
            Self::Bl => "BL",
            Self::Bm => "BM",
            Self::Bn => "BN",
            Self::Bo => "BO",
            Self::Bq => "BQ",
            Self::Br => "BR",
            Self::Bs => "BS",
            Self::Bt => "BT",
            Self::Bv => "BV",
            Self::Bw => "BW",
            Self::By => "BY",
            Self::Bz => "BZ",
            Self::Ca => "CA",
            Self::Cc => "CC",
            Self::Cd => "CD",
            Self::Cf => "CF",
            Self::Cg => "CG",
            Self::Ch => "CH",
            Self::Ci => "CI",
            Self::Ck => "CK",
            Self::Cl => "CL",
            Self::Cm => "CM",
            Self::Cn => "CN",
            Self::Co => "CO",
            Self::Cr => "CR",
            Self::Cu => "CU",
            Self::Cv => "CV",
            Self::Cw => "CW",
            Self::Cx => "CX",
            Self::Cy => "CY",
            Self::Cz => "CZ",
            Self::De => "DE",
            Self::Dj => "DJ",
            Self::Dk => "DK",
            Self::Dm => "DM",
            Self::Do => "DO",
            Self::Dz => "DZ",
            Self::Ec => "EC",
            Self::Ee => "EE",
            Self::Eg => "EG",
            Self::Eh => "EH",
            Self::Er => "ER",
            Self::Es => "ES",
            Self::Et => "ET",
            Self::Fi => "FI",
            Self::Fj => "FJ",
            Self::Fk => "FK",
            Self::Fm => "FM",
            Self::Fo => "FO",
            Self::Fr => "FR",
            Self::Ga => "GA",
            Self::Gb => "GB",
            Self::Gd => "GD",
            Self::Ge => "GE",
            Self::Gf => "GF",
            Self::Gg => "GG",
            Self::Gh => "GH",
            Self::Gi => "GI",
            Self::Gl => "GL",
            Self::Gm => "GM",
            Self::Gn => "GN",
            Self::Gp => "GP",
            Self::Gq => "GQ",
            Self::Gr => "GR",
            Self::Gs => "GS",
            Self::Gt => "GT",
            Self::Gu => "GU",
            Self::Gw => "GW",
            Self::Gy => "GY",
            Self::Hk => "HK",
            Self::Hm => "HM",
            Self::Hn => "HN",
            Self::Hr => "HR",
            Self::Ht => "HT",
            Self::Hu => "HU",
            Self::Id => "ID",
            Self::Ie => "IE",
            Self::Il => "IL",
            Self::Im => "IM",
            Self::In => "IN",
            Self::Io => "IO",
            Self::Iq => "IQ",
            Self::Ir => "IR",
            Self::Is => "IS",
            Self::It => "IT",
            Self::Je => "JE",
            Self::Jm => "JM",
            Self::Jo => "JO",
            Self::Jp => "JP",
            Self::Ke => "KE",
            Self::Kg => "KG",
            Self::Kh => "KH",
            Self::Ki => "KI",
            Self::Km => "KM",
            Self::Kn => "KN",
            Self::Kp => "KP",
            Self::Kr => "KR",
            Self::Kw => "KW",
            Self::Ky => "KY",
            Self::Kz => "KZ",
            Self::La => "LA",
            Self::Lb => "LB",
            Self::Lc => "LC",
            Self::Li => "LI",
            Self::Lk => "LK",
            Self::Lr => "LR",
            Self::Ls => "LS",
            Self::Lt => "LT",
            Self::Lu => "LU",
            Self::Lv => "LV",
            Self::Ly => "LY",
            Self::Ma => "MA",
            Self::Mc => "MC",
            Self::Md => "MD",
            Self::Me => "ME",
            Self::Mf => "MF",
            Self::Mg => "MG",
            Self::Mh => "MH",
            Self::Mk => "MK",
            Self::Ml => "ML",
            Self::Mm => "MM",
            Self::Mn => "MN",
            Self::Mo => "MO",
            Self::Mp => "MP",
            Self::Mq => "MQ",
            Self::Mr => "MR",
            Self::Ms => "MS",
            Self::Mt => "MT",
            Self::Mu => "MU",
            Self::Mv => "MV",
            Self::Mw => "MW",
            Self::Mx => "MX",
            Self::My => "MY",
            Self::Mz => "MZ",
            Self::Na => "NA",
            Self::Nc => "NC",
            Self::Ne => "NE",
            Self::Nf => "NF",
            Self::Ng => "NG",
            Self::Ni => "NI",
            Self::Nl => "NL",
            Self::No => "NO",
            Self::Np => "NP",
            Self::Nr => "NR",
            Self::Nu => "NU",
            Self::Nz => "NZ",
            Self::Om => "OM",
            Self::Pa => "PA",
            Self::Pe => "PE",
            Self::Pf => "PF",
            Self::Pg => "PG",
            Self::Ph => "PH",
            Self::Pk => "PK",
            Self::Pl => "PL",
            Self::Pm => "PM",
            Self::Pn => "PN",
            Self::Pr => "PR",
            Self::Ps => "PS",
            Self::Pt => "PT",
            Self::Pw => "PW",
            Self::Py => "PY",
            Self::Qa => "QA",
            Self::Re => "RE",
            Self::Ro => "RO",
            Self::Rs => "RS",
            Self::Ru => "RU",
            Self::Rw => "RW",
            Self::Sa => "SA",
            Self::Sb => "SB",
            Self::Sc => "SC",
            Self::Sd => "SD",
            Self::Se => "SE",
            Self::Sg => "SG",
            Self::Sh => "SH",
            Self::Si => "SI",
            Self::Sj => "SJ",
            Self::Sk => "SK",
            Self::Sl => "SL",
            Self::Sm => "SM",
            Self::Sn => "SN",
            Self::So => "SO",
            Self::Sr => "SR",
            Self::Ss => "SS",
            Self::St => "ST",
            Self::Sv => "SV",
            Self::Sx => "SX",
            Self::Sy => "SY",
            Self::Sz => "SZ",
            Self::Tc => "TC",
            Self::Td => "TD",
            Self::Tf => "TF",
            Self::Tg => "TG",
            Self::Th => "TH",
            Self::Tj => "TJ",
            Self::Tk => "TK",
            Self::Tl => "TL",
            Self::Tm => "TM",
            Self::Tn => "TN",
            Self::To => "TO",
            Self::Tr => "TR",
            Self::Tt => "TT",
            Self::Tv => "TV",
            Self::Tw => "TW",
            Self::Tz => "TZ",
            Self::Ua => "UA",
            Self::Ug => "UG",
            Self::Um => "UM",
            Self::Us => "US",
            Self::Uy => "UY",
            Self::Uz => "UZ",
            Self::Va => "VA",
            Self::Vc => "VC",
            Self::Ve => "VE",
            Self::Vg => "VG",
            Self::Vi => "VI",
            Self::Vn => "VN",
            Self::Vu => "VU",
            Self::Wf => "WF",
            Self::Ws => "WS",
            Self::Ye => "YE",
            Self::Yt => "YT",
            Self::Za => "ZA",
            Self::Zm => "ZM",
            Self::Zw => "ZW",
        }
    }

    /// Returns the English short country name used by ISO 3166/MA (title case).
    ///
    /// # Examples
    ///
    /// ```rust
    /// use mollie_rs::CountryCode;
    ///
    /// assert_eq!(CountryCode::DE.name(), "Germany");
    /// assert_eq!(CountryCode::BO.name(), "Bolivia, Plurinational State of");
    /// ```
    pub const fn name(self) -> &'static str {
        match self {
            Self::Ad => "Andorra",
            Self::Ae => "United Arab Emirates",
            Self::Af => "Afghanistan",
            Self::Ag => "Antigua and Barbuda",
            Self::Ai => "Anguilla",
            Self::Al => "Albania",
            Self::Am => "Armenia",
            Self::An => "Netherlands Antilles (historically assigned; transitional ISO code)",
            Self::Ao => "Angola",
            Self::Aq => "Antarctica",
            Self::Ar => "Argentina",
            Self::As => "American Samoa",
            Self::At => "Austria",
            Self::Au => "Australia",
            Self::Aw => "Aruba",
            Self::Ax => "Åland Islands",
            Self::Az => "Azerbaijan",
            Self::Ba => "Bosnia and Herzegovina",
            Self::Bb => "Barbados",
            Self::Bd => "Bangladesh",
            Self::Be => "Belgium",
            Self::Bf => "Burkina Faso",
            Self::Bg => "Bulgaria",
            Self::Bh => "Bahrain",
            Self::Bi => "Burundi",
            Self::Bj => "Benin",
            Self::Bl => "Saint Barthélemy",
            Self::Bm => "Bermuda",
            Self::Bn => "Brunei Darussalam",
            Self::Bo => "Bolivia, Plurinational State of",
            Self::Bq => "Bonaire, Sint Eustatius and Saba",
            Self::Br => "Brazil",
            Self::Bs => "Bahamas",
            Self::Bt => "Bhutan",
            Self::Bv => "Bouvet Island",
            Self::Bw => "Botswana",
            Self::By => "Belarus",
            Self::Bz => "Belize",
            Self::Ca => "Canada",
            Self::Cc => "Cocos (Keeling) Islands",
            Self::Cd => "Congo, Democratic Republic of the",
            Self::Cf => "Central African Republic",
            Self::Cg => "Congo",
            Self::Ch => "Switzerland",
            Self::Ci => "Côte d'Ivoire",
            Self::Ck => "Cook Islands",
            Self::Cl => "Chile",
            Self::Cm => "Cameroon",
            Self::Cn => "China",
            Self::Co => "Colombia",
            Self::Cr => "Costa Rica",
            Self::Cu => "Cuba",
            Self::Cv => "Cabo Verde",
            Self::Cw => "Curaçao",
            Self::Cx => "Christmas Island",
            Self::Cy => "Cyprus",
            Self::Cz => "Czechia",
            Self::De => "Germany",
            Self::Dj => "Djibouti",
            Self::Dk => "Denmark",
            Self::Dm => "Dominica",
            Self::Do => "Dominican Republic",
            Self::Dz => "Algeria",
            Self::Ec => "Ecuador",
            Self::Ee => "Estonia",
            Self::Eg => "Egypt",
            Self::Eh => "Western Sahara",
            Self::Er => "Eritrea",
            Self::Es => "Spain",
            Self::Et => "Ethiopia",
            Self::Fi => "Finland",
            Self::Fj => "Fiji",
            Self::Fk => "Falkland Islands (Malvinas)",
            Self::Fm => "Micronesia, Federated States of",
            Self::Fo => "Faroe Islands",
            Self::Fr => "France",
            Self::Ga => "Gabon",
            Self::Gb => "United Kingdom of Great Britain and Northern Ireland",
            Self::Gd => "Grenada",
            Self::Ge => "Georgia",
            Self::Gf => "French Guiana",
            Self::Gg => "Guernsey",
            Self::Gh => "Ghana",
            Self::Gi => "Gibraltar",
            Self::Gl => "Greenland",
            Self::Gm => "Gambia",
            Self::Gn => "Guinea",
            Self::Gp => "Guadeloupe",
            Self::Gq => "Equatorial Guinea",
            Self::Gr => "Greece",
            Self::Gs => "South Georgia and the South Sandwich Islands",
            Self::Gt => "Guatemala",
            Self::Gu => "Guam",
            Self::Gw => "Guinea-Bissau",
            Self::Gy => "Guyana",
            Self::Hk => "Hong Kong",
            Self::Hm => "Heard Island and McDonald Islands",
            Self::Hn => "Honduras",
            Self::Hr => "Croatia",
            Self::Ht => "Haiti",
            Self::Hu => "Hungary",
            Self::Id => "Indonesia",
            Self::Ie => "Ireland",
            Self::Il => "Israel",
            Self::Im => "Isle of Man",
            Self::In => "India",
            Self::Io => "British Indian Ocean Territory",
            Self::Iq => "Iraq",
            Self::Ir => "Iran, Islamic Republic of",
            Self::Is => "Iceland",
            Self::It => "Italy",
            Self::Je => "Jersey",
            Self::Jm => "Jamaica",
            Self::Jo => "Jordan",
            Self::Jp => "Japan",
            Self::Ke => "Kenya",
            Self::Kg => "Kyrgyzstan",
            Self::Kh => "Cambodia",
            Self::Ki => "Kiribati",
            Self::Km => "Comoros",
            Self::Kn => "Saint Kitts and Nevis",
            Self::Kp => "Korea, Democratic People's Republic of",
            Self::Kr => "Korea, Republic of",
            Self::Kw => "Kuwait",
            Self::Ky => "Cayman Islands",
            Self::Kz => "Kazakhstan",
            Self::La => "Lao People's Democratic Republic",
            Self::Lb => "Lebanon",
            Self::Lc => "Saint Lucia",
            Self::Li => "Liechtenstein",
            Self::Lk => "Sri Lanka",
            Self::Lr => "Liberia",
            Self::Ls => "Lesotho",
            Self::Lt => "Lithuania",
            Self::Lu => "Luxembourg",
            Self::Lv => "Latvia",
            Self::Ly => "Libya",
            Self::Ma => "Morocco",
            Self::Mc => "Monaco",
            Self::Md => "Moldova, Republic of",
            Self::Me => "Montenegro",
            Self::Mf => "Saint Martin (French part)",
            Self::Mg => "Madagascar",
            Self::Mh => "Marshall Islands",
            Self::Mk => "North Macedonia",
            Self::Ml => "Mali",
            Self::Mm => "Myanmar",
            Self::Mn => "Mongolia",
            Self::Mo => "Macao",
            Self::Mp => "Northern Mariana Islands",
            Self::Mq => "Martinique",
            Self::Mr => "Mauritania",
            Self::Ms => "Montserrat",
            Self::Mt => "Malta",
            Self::Mu => "Mauritius",
            Self::Mv => "Maldives",
            Self::Mw => "Malawi",
            Self::Mx => "Mexico",
            Self::My => "Malaysia",
            Self::Mz => "Mozambique",
            Self::Na => "Namibia",
            Self::Nc => "New Caledonia",
            Self::Ne => "Niger",
            Self::Nf => "Norfolk Island",
            Self::Ng => "Nigeria",
            Self::Ni => "Nicaragua",
            Self::Nl => "Netherlands, Kingdom of the",
            Self::No => "Norway",
            Self::Np => "Nepal",
            Self::Nr => "Nauru",
            Self::Nu => "Niue",
            Self::Nz => "New Zealand",
            Self::Om => "Oman",
            Self::Pa => "Panama",
            Self::Pe => "Peru",
            Self::Pf => "French Polynesia",
            Self::Pg => "Papua New Guinea",
            Self::Ph => "Philippines",
            Self::Pk => "Pakistan",
            Self::Pl => "Poland",
            Self::Pm => "Saint Pierre and Miquelon",
            Self::Pn => "Pitcairn",
            Self::Pr => "Puerto Rico",
            Self::Ps => "Palestine, State of",
            Self::Pt => "Portugal",
            Self::Pw => "Palau",
            Self::Py => "Paraguay",
            Self::Qa => "Qatar",
            Self::Re => "Réunion",
            Self::Ro => "Romania",
            Self::Rs => "Serbia",
            Self::Ru => "Russian Federation",
            Self::Rw => "Rwanda",
            Self::Sa => "Saudi Arabia",
            Self::Sb => "Solomon Islands",
            Self::Sc => "Seychelles",
            Self::Sd => "Sudan",
            Self::Se => "Sweden",
            Self::Sg => "Singapore",
            Self::Sh => "Saint Helena, Ascension and Tristan da Cunha",
            Self::Si => "Slovenia",
            Self::Sj => "Svalbard and Jan Mayen",
            Self::Sk => "Slovakia",
            Self::Sl => "Sierra Leone",
            Self::Sm => "San Marino",
            Self::Sn => "Senegal",
            Self::So => "Somalia",
            Self::Sr => "Suriname",
            Self::Ss => "South Sudan",
            Self::St => "Sao Tome and Principe",
            Self::Sv => "El Salvador",
            Self::Sx => "Sint Maarten (Dutch part)",
            Self::Sy => "Syrian Arab Republic",
            Self::Sz => "Eswatini",
            Self::Tc => "Turks and Caicos Islands",
            Self::Td => "Chad",
            Self::Tf => "French Southern Territories",
            Self::Tg => "Togo",
            Self::Th => "Thailand",
            Self::Tj => "Tajikistan",
            Self::Tk => "Tokelau",
            Self::Tl => "Timor-Leste",
            Self::Tm => "Turkmenistan",
            Self::Tn => "Tunisia",
            Self::To => "Tonga",
            Self::Tr => "Türkiye",
            Self::Tt => "Trinidad and Tobago",
            Self::Tv => "Tuvalu",
            Self::Tw => "Taiwan, Province of China",
            Self::Tz => "Tanzania, United Republic of",
            Self::Ua => "Ukraine",
            Self::Ug => "Uganda",
            Self::Um => "United States Minor Outlying Islands",
            Self::Us => "United States of America",
            Self::Uy => "Uruguay",
            Self::Uz => "Uzbekistan",
            Self::Va => "Holy See",
            Self::Vc => "Saint Vincent and the Grenadines",
            Self::Ve => "Venezuela, Bolivarian Republic of",
            Self::Vg => "Virgin Islands (British)",
            Self::Vi => "Virgin Islands (U.S.)",
            Self::Vn => "Viet Nam",
            Self::Vu => "Vanuatu",
            Self::Wf => "Wallis and Futuna",
            Self::Ws => "Samoa",
            Self::Ye => "Yemen",
            Self::Yt => "Mayotte",
            Self::Za => "South Africa",
            Self::Zm => "Zambia",
            Self::Zw => "Zimbabwe",
        }
    }

    /// Returns a short summary of ISO 3166-2 subdivision categories for this country,
    /// when documented.
    ///
    /// This is **not** a full list of subdivision codes (e.g. `NL-NH`); it only
    /// describes how many / which kinds of subdivisions are coded.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use mollie_rs::CountryCode;
    ///
    /// assert_eq!(CountryCode::AD.subdivisions(), Some("7 parishes"));
    /// assert_eq!(CountryCode::AQ.subdivisions(), None);
    /// ```
    pub const fn subdivisions(self) -> Option<&'static str> {
        match self {
            Self::Ad => Some("7 parishes"),
            Self::Ae => Some("emirates"),
            Self::Af => Some("34 provinces"),
            Self::Ag => Some("6 parishes, 2 dependencies"),
            Self::Ai => None,
            Self::Al => Some("12 counties"),
            Self::Am => Some("1 city, 10 regions"),
            Self::An => None,
            Self::Ao => Some("18 provinces"),
            Self::Aq => None,
            Self::Ar => Some("1 city, 23 provinces"),
            Self::As => None,
            Self::At => Some("9 states"),
            Self::Au => Some("6 states, 2 territories"),
            Self::Aw => None,
            Self::Ax => None,
            Self::Az => Some("1 autonomous republic, 11 municipalities, 66 rayons"),
            Self::Ba => Some("entities, 1 district with special status"),
            Self::Bb => Some("11 parishes"),
            Self::Bd => Some("8 divisions, 64 districts"),
            Self::Be => Some("3 regions, 10 provinces"),
            Self::Bf => Some("regions, 45 provinces"),
            Self::Bg => Some("28 regions"),
            Self::Bh => Some("4 governorates"),
            Self::Bi => Some("18 provinces"),
            Self::Bj => Some("12 departments"),
            Self::Bl => None,
            Self::Bm => None,
            Self::Bn => Some("districts"),
            Self::Bo => Some("departments"),
            Self::Bq => Some("special municipalities"),
            Self::Br => Some("1 federal district, 26 states"),
            Self::Bs => Some("31 districts, 1 island"),
            Self::Bt => Some("20 districts"),
            Self::Bv => None,
            Self::Bw => Some("10 districts, 4 towns, 2 cities"),
            Self::By => Some("6 oblasts, 1 city"),
            Self::Bz => Some("6 districts"),
            Self::Ca => Some("10 provinces, 3 territories"),
            Self::Cc => None,
            Self::Cd => Some("1 city, 25 provinces"),
            Self::Cf => Some("1 commune, 14 prefectures, 2 economic prefectures"),
            Self::Cg => Some("12 departments"),
            Self::Ch => Some("26 cantons"),
            Self::Ci => Some("districts, 2 autonomous districts"),
            Self::Ck => None,
            Self::Cl => Some("16 regions"),
            Self::Cm => Some("10 regions"),
            Self::Cn => Some("4 municipalities, 23 provinces, 5 autonomous regions, 2 special administrative regions"),
            Self::Co => Some("1 capital district, 32 departments"),
            Self::Cr => Some("provinces"),
            Self::Cu => Some("15 provinces, 1 special municipality"),
            Self::Cv => Some("geographical regions, 22 municipalities"),
            Self::Cw => None,
            Self::Cx => None,
            Self::Cy => Some("6 districts"),
            Self::Cz => Some("13 regions, 1 capital city, 76 districts"),
            Self::De => Some("16 states"),
            Self::Dj => Some("5 regions, 1 city"),
            Self::Dk => Some("5 regions"),
            Self::Dm => Some("10 parishes"),
            Self::Do => Some("regions, 1 district, 31 provinces"),
            Self::Dz => Some("58 provinces"),
            Self::Ec => Some("24 provinces"),
            Self::Ee => Some("15 counties, 64 rural municipalities, 15 urban municipalities"),
            Self::Eg => Some("27 governorates"),
            Self::Eh => None,
            Self::Er => Some("6 regions"),
            Self::Es => Some("17 autonomous communities, 2 autonomous cities in North Africa, 50 provinces"),
            Self::Et => Some("2 administrations, 11 regional states"),
            Self::Fi => Some("19 regions"),
            Self::Fj => Some("4 divisions, 1 dependency, 14 provinces"),
            Self::Fk => None,
            Self::Fm => Some("states"),
            Self::Fo => None,
            Self::Fr => Some("12 metropolitan regions and overseas collectivities/territories; 95 metropolitan departments and related entities"),
            Self::Ga => Some("9 provinces"),
            Self::Gb => Some("countries, province, council areas, counties, districts, unitary authorities, metropolitan districts, London boroughs, city corporation"),
            Self::Gd => Some("6 parishes, 1 dependency"),
            Self::Ge => Some("2 autonomous republics, 1 city, 9 regions"),
            Self::Gf => None,
            Self::Gg => None,
            Self::Gh => Some("16 regions"),
            Self::Gi => None,
            Self::Gl => Some("5 municipalities"),
            Self::Gm => Some("1 city, 5 divisions"),
            Self::Gn => Some("7 administrative regions, 1 governorate, 33 prefectures"),
            Self::Gp => None,
            Self::Gq => Some("regions, 8 provinces"),
            Self::Gr => Some("13 administrative regions, 1 self-governed part"),
            Self::Gs => None,
            Self::Gt => Some("22 departments"),
            Self::Gu => None,
            Self::Gw => Some("3 provinces, 1 autonomous sector, 8 regions"),
            Self::Gy => Some("10 regions"),
            Self::Hk => None,
            Self::Hm => None,
            Self::Hn => Some("18 departments"),
            Self::Hr => Some("1 city, 20 counties"),
            Self::Ht => Some("10 departments"),
            Self::Hu => Some("1 capital city, 19 counties, 23 cities of county right"),
            Self::Id => Some("7 geographical units, 36 provinces, 1 capital district, 1 special region"),
            Self::Ie => Some("4 provinces, 26 counties"),
            Self::Il => Some("6 districts"),
            Self::Im => None,
            Self::In => Some("28 states, 8 union territories"),
            Self::Io => None,
            Self::Iq => Some("1 region, 18 governorates"),
            Self::Ir => Some("provinces"),
            Self::Is => Some("8 regions, 64 municipalities"),
            Self::It => Some("15 regions, 5 autonomous regions, provinces, free municipal consortiums, metropolitan cities, decentralized regional entities"),
            Self::Je => None,
            Self::Jm => Some("14 parishes"),
            Self::Jo => Some("12 governorates"),
            Self::Jp => Some("47 prefectures"),
            Self::Ke => Some("47 counties"),
            Self::Kg => Some("2 cities, 7 regions"),
            Self::Kh => Some("1 autonomous municipality, 24 provinces"),
            Self::Ki => Some("3 groups of islands"),
            Self::Km => Some("3 islands"),
            Self::Kn => Some("states, 14 parishes"),
            Self::Kp => Some("capital city, metropolitan city, special city, 9 provinces"),
            Self::Kr => Some("metropolitan cities, special cities, special self-governing city, provinces, special self-governing provinces"),
            Self::Kw => Some("6 governorates"),
            Self::Ky => None,
            Self::Kz => Some("3 cities, 17 regions"),
            Self::La => Some("1 prefecture, 17 provinces"),
            Self::Lb => Some("8 governorates"),
            Self::Lc => Some("districts"),
            Self::Li => Some("11 communes"),
            Self::Lk => Some("provinces, 25 districts"),
            Self::Lr => Some("15 counties"),
            Self::Ls => Some("10 districts"),
            Self::Lt => Some("10 counties, 9 municipalities, 7 city municipalities, 44 district municipalities"),
            Self::Lu => Some("12 cantons"),
            Self::Lv => Some("36 municipalities, 7 state cities"),
            Self::Ly => Some("22 popularates"),
            Self::Ma => Some("12 regions, 62 provinces, 13 prefectures"),
            Self::Mc => Some("17 quarters"),
            Self::Md => Some("autonomous territorial unit, 3 cities, 32 districts, 1 territorial unit"),
            Self::Me => Some("25 municipalities"),
            Self::Mf => None,
            Self::Mg => Some("6 provinces"),
            Self::Mh => Some("chains of islands, 24 municipalities"),
            Self::Mk => Some("municipalities"),
            Self::Ml => Some("1 district, 10 regions"),
            Self::Mm => Some("7 regions, 7 states, 1 union territory"),
            Self::Mn => Some("1 capital city, 21 provinces"),
            Self::Mo => None,
            Self::Mp => None,
            Self::Mq => None,
            Self::Mr => Some("15 regions"),
            Self::Ms => None,
            Self::Mt => Some("68 local councils"),
            Self::Mu => Some("3 dependencies, 9 districts"),
            Self::Mv => Some("19 administrative atolls, 2 cities"),
            Self::Mw => Some("3 regions, 28 districts"),
            Self::Mx => Some("31 states, 1 federal entity"),
            Self::My => Some("3 federal territories, 13 states"),
            Self::Mz => Some("1 city, 10 provinces"),
            Self::Na => Some("14 regions"),
            Self::Nc => None,
            Self::Ne => Some("1 urban community, 7 departments"),
            Self::Nf => None,
            Self::Ng => Some("1 capital territory, 36 states"),
            Self::Ni => Some("15 departments, 2 autonomous regions"),
            Self::Nl => Some("provinces, 3 countries, 3 special municipalities"),
            Self::No => Some("11 counties, 2 arctic regions"),
            Self::Np => Some("7 provinces"),
            Self::Nr => Some("14 districts"),
            Self::Nu => None,
            Self::Nz => Some("regions, 1 special island authority"),
            Self::Om => Some("11 governorates"),
            Self::Pa => Some("10 provinces, 4 indigenous regions"),
            Self::Pe => Some("25 regions, 1 municipality"),
            Self::Pf => None,
            Self::Pg => Some("1 district, 20 provinces, 1 autonomous region"),
            Self::Ph => Some("17 regions, 82 provinces"),
            Self::Pk => Some("4 provinces, 2 autonomous territories, 1 federal territory"),
            Self::Pl => Some("16 voivodships"),
            Self::Pm => None,
            Self::Pn => None,
            Self::Pr => None,
            Self::Ps => Some("governorates"),
            Self::Pt => Some("18 districts, 2 autonomous regions"),
            Self::Pw => Some("16 states"),
            Self::Py => Some("1 capital, 17 departments"),
            Self::Qa => Some("8 municipalities"),
            Self::Re => None,
            Self::Ro => Some("41 departments, 1 municipality"),
            Self::Rs => Some("2 autonomous provinces, 1 city, 29 districts"),
            Self::Ru => Some("republics, administrative territories, administrative regions, autonomous cities, autonomous region, autonomous districts"),
            Self::Rw => Some("1 town council, 4 provinces"),
            Self::Sa => Some("regions"),
            Self::Sb => Some("1 capital territory, 9 provinces"),
            Self::Sc => Some("27 districts"),
            Self::Sd => Some("18 states"),
            Self::Se => Some("21 counties"),
            Self::Sg => Some("5 districts"),
            Self::Sh => Some("geographical entities"),
            Self::Si => Some("200 municipalities and 12 urban municipalities"),
            Self::Sj => None,
            Self::Sk => Some("8 regions"),
            Self::Sl => Some("area, 4 provinces"),
            Self::Sm => Some("municipalities"),
            Self::Sn => Some("14 regions"),
            Self::So => Some("18 regions"),
            Self::Sr => Some("10 districts"),
            Self::Ss => Some("states"),
            Self::St => Some("1 autonomous region, 6 districts"),
            Self::Sv => Some("departments"),
            Self::Sx => None,
            Self::Sy => Some("provinces"),
            Self::Sz => Some("4 regions"),
            Self::Tc => None,
            Self::Td => Some("23 provinces"),
            Self::Tf => None,
            Self::Tg => Some("5 regions"),
            Self::Th => Some("1 metropolitan administration, 1 special administrative city, 76 provinces"),
            Self::Tj => Some("1 autonomous region, 2 regions, 1 capital territory, 1 district under republic administration"),
            Self::Tk => None,
            Self::Tl => Some("12 municipalities, 1 special administrative region"),
            Self::Tm => Some("5 regions, 1 city"),
            Self::Tn => Some("24 governorates"),
            Self::To => Some("5 divisions"),
            Self::Tr => Some("81 provinces"),
            Self::Tt => Some("regions, 3 boroughs, 2 cities, 1 ward"),
            Self::Tv => Some("1 town council, 7 island councils"),
            Self::Tw => Some("counties, 3 cities, 6 special municipalities"),
            Self::Tz => Some("regions"),
            Self::Ua => Some("24 regions, 1 republic, 2 cities"),
            Self::Ug => Some("4 geographical regions, 134 districts, 1 city"),
            Self::Um => Some("islands, groups of islands"),
            Self::Us => Some("states, 1 district, 6 outlying areas"),
            Self::Uy => Some("19 departments"),
            Self::Uz => Some("1 city, 12 regions, 1 republic"),
            Self::Va => None,
            Self::Vc => Some("parishes"),
            Self::Ve => Some("federal dependency, 1 federal district, 23 states"),
            Self::Vg => None,
            Self::Vi => None,
            Self::Vn => Some("provinces, 5 municipalities"),
            Self::Vu => Some("6 provinces"),
            Self::Wf => Some("administrative precincts"),
            Self::Ws => Some("11 districts"),
            Self::Ye => Some("1 municipality, 21 governorates"),
            Self::Yt => None,
            Self::Za => Some("provinces"),
            Self::Zm => Some("10 provinces"),
            Self::Zw => Some("10 provinces"),
        }
    }

    /// Returns true when `value` is a recognized ISO 3166-1 alpha-2 code.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use mollie_rs::CountryCode;
    ///
    /// assert!(CountryCode::is_valid("DE"));
    /// assert!(!CountryCode::is_valid("XX"));
    /// ```
    pub fn is_valid(value: impl AsRef<str>) -> bool {
        Self::parse(value).is_ok()
    }

    /// Returns true when `value` matches the ISO 3166-1 alpha-2 *format*
    /// (exactly two ASCII uppercase letters), without checking assignment.
    pub fn is_valid_format(value: impl AsRef<str>) -> bool {
        let b = value.as_ref().as_bytes();
        b.len() == 2 && b[0].is_ascii_uppercase() && b[1].is_ascii_uppercase()
    }
}

impl FromStr for CountryCode {
    type Err = MollieError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "AD" => Ok(Self::Ad),
            "AE" => Ok(Self::Ae),
            "AF" => Ok(Self::Af),
            "AG" => Ok(Self::Ag),
            "AI" => Ok(Self::Ai),
            "AL" => Ok(Self::Al),
            "AM" => Ok(Self::Am),
            "AN" => Ok(Self::An),
            "AO" => Ok(Self::Ao),
            "AQ" => Ok(Self::Aq),
            "AR" => Ok(Self::Ar),
            "AS" => Ok(Self::As),
            "AT" => Ok(Self::At),
            "AU" => Ok(Self::Au),
            "AW" => Ok(Self::Aw),
            "AX" => Ok(Self::Ax),
            "AZ" => Ok(Self::Az),
            "BA" => Ok(Self::Ba),
            "BB" => Ok(Self::Bb),
            "BD" => Ok(Self::Bd),
            "BE" => Ok(Self::Be),
            "BF" => Ok(Self::Bf),
            "BG" => Ok(Self::Bg),
            "BH" => Ok(Self::Bh),
            "BI" => Ok(Self::Bi),
            "BJ" => Ok(Self::Bj),
            "BL" => Ok(Self::Bl),
            "BM" => Ok(Self::Bm),
            "BN" => Ok(Self::Bn),
            "BO" => Ok(Self::Bo),
            "BQ" => Ok(Self::Bq),
            "BR" => Ok(Self::Br),
            "BS" => Ok(Self::Bs),
            "BT" => Ok(Self::Bt),
            "BV" => Ok(Self::Bv),
            "BW" => Ok(Self::Bw),
            "BY" => Ok(Self::By),
            "BZ" => Ok(Self::Bz),
            "CA" => Ok(Self::Ca),
            "CC" => Ok(Self::Cc),
            "CD" => Ok(Self::Cd),
            "CF" => Ok(Self::Cf),
            "CG" => Ok(Self::Cg),
            "CH" => Ok(Self::Ch),
            "CI" => Ok(Self::Ci),
            "CK" => Ok(Self::Ck),
            "CL" => Ok(Self::Cl),
            "CM" => Ok(Self::Cm),
            "CN" => Ok(Self::Cn),
            "CO" => Ok(Self::Co),
            "CR" => Ok(Self::Cr),
            "CU" => Ok(Self::Cu),
            "CV" => Ok(Self::Cv),
            "CW" => Ok(Self::Cw),
            "CX" => Ok(Self::Cx),
            "CY" => Ok(Self::Cy),
            "CZ" => Ok(Self::Cz),
            "DE" => Ok(Self::De),
            "DJ" => Ok(Self::Dj),
            "DK" => Ok(Self::Dk),
            "DM" => Ok(Self::Dm),
            "DO" => Ok(Self::Do),
            "DZ" => Ok(Self::Dz),
            "EC" => Ok(Self::Ec),
            "EE" => Ok(Self::Ee),
            "EG" => Ok(Self::Eg),
            "EH" => Ok(Self::Eh),
            "ER" => Ok(Self::Er),
            "ES" => Ok(Self::Es),
            "ET" => Ok(Self::Et),
            "FI" => Ok(Self::Fi),
            "FJ" => Ok(Self::Fj),
            "FK" => Ok(Self::Fk),
            "FM" => Ok(Self::Fm),
            "FO" => Ok(Self::Fo),
            "FR" => Ok(Self::Fr),
            "GA" => Ok(Self::Ga),
            "GB" => Ok(Self::Gb),
            "GD" => Ok(Self::Gd),
            "GE" => Ok(Self::Ge),
            "GF" => Ok(Self::Gf),
            "GG" => Ok(Self::Gg),
            "GH" => Ok(Self::Gh),
            "GI" => Ok(Self::Gi),
            "GL" => Ok(Self::Gl),
            "GM" => Ok(Self::Gm),
            "GN" => Ok(Self::Gn),
            "GP" => Ok(Self::Gp),
            "GQ" => Ok(Self::Gq),
            "GR" => Ok(Self::Gr),
            "GS" => Ok(Self::Gs),
            "GT" => Ok(Self::Gt),
            "GU" => Ok(Self::Gu),
            "GW" => Ok(Self::Gw),
            "GY" => Ok(Self::Gy),
            "HK" => Ok(Self::Hk),
            "HM" => Ok(Self::Hm),
            "HN" => Ok(Self::Hn),
            "HR" => Ok(Self::Hr),
            "HT" => Ok(Self::Ht),
            "HU" => Ok(Self::Hu),
            "ID" => Ok(Self::Id),
            "IE" => Ok(Self::Ie),
            "IL" => Ok(Self::Il),
            "IM" => Ok(Self::Im),
            "IN" => Ok(Self::In),
            "IO" => Ok(Self::Io),
            "IQ" => Ok(Self::Iq),
            "IR" => Ok(Self::Ir),
            "IS" => Ok(Self::Is),
            "IT" => Ok(Self::It),
            "JE" => Ok(Self::Je),
            "JM" => Ok(Self::Jm),
            "JO" => Ok(Self::Jo),
            "JP" => Ok(Self::Jp),
            "KE" => Ok(Self::Ke),
            "KG" => Ok(Self::Kg),
            "KH" => Ok(Self::Kh),
            "KI" => Ok(Self::Ki),
            "KM" => Ok(Self::Km),
            "KN" => Ok(Self::Kn),
            "KP" => Ok(Self::Kp),
            "KR" => Ok(Self::Kr),
            "KW" => Ok(Self::Kw),
            "KY" => Ok(Self::Ky),
            "KZ" => Ok(Self::Kz),
            "LA" => Ok(Self::La),
            "LB" => Ok(Self::Lb),
            "LC" => Ok(Self::Lc),
            "LI" => Ok(Self::Li),
            "LK" => Ok(Self::Lk),
            "LR" => Ok(Self::Lr),
            "LS" => Ok(Self::Ls),
            "LT" => Ok(Self::Lt),
            "LU" => Ok(Self::Lu),
            "LV" => Ok(Self::Lv),
            "LY" => Ok(Self::Ly),
            "MA" => Ok(Self::Ma),
            "MC" => Ok(Self::Mc),
            "MD" => Ok(Self::Md),
            "ME" => Ok(Self::Me),
            "MF" => Ok(Self::Mf),
            "MG" => Ok(Self::Mg),
            "MH" => Ok(Self::Mh),
            "MK" => Ok(Self::Mk),
            "ML" => Ok(Self::Ml),
            "MM" => Ok(Self::Mm),
            "MN" => Ok(Self::Mn),
            "MO" => Ok(Self::Mo),
            "MP" => Ok(Self::Mp),
            "MQ" => Ok(Self::Mq),
            "MR" => Ok(Self::Mr),
            "MS" => Ok(Self::Ms),
            "MT" => Ok(Self::Mt),
            "MU" => Ok(Self::Mu),
            "MV" => Ok(Self::Mv),
            "MW" => Ok(Self::Mw),
            "MX" => Ok(Self::Mx),
            "MY" => Ok(Self::My),
            "MZ" => Ok(Self::Mz),
            "NA" => Ok(Self::Na),
            "NC" => Ok(Self::Nc),
            "NE" => Ok(Self::Ne),
            "NF" => Ok(Self::Nf),
            "NG" => Ok(Self::Ng),
            "NI" => Ok(Self::Ni),
            "NL" => Ok(Self::Nl),
            "NO" => Ok(Self::No),
            "NP" => Ok(Self::Np),
            "NR" => Ok(Self::Nr),
            "NU" => Ok(Self::Nu),
            "NZ" => Ok(Self::Nz),
            "OM" => Ok(Self::Om),
            "PA" => Ok(Self::Pa),
            "PE" => Ok(Self::Pe),
            "PF" => Ok(Self::Pf),
            "PG" => Ok(Self::Pg),
            "PH" => Ok(Self::Ph),
            "PK" => Ok(Self::Pk),
            "PL" => Ok(Self::Pl),
            "PM" => Ok(Self::Pm),
            "PN" => Ok(Self::Pn),
            "PR" => Ok(Self::Pr),
            "PS" => Ok(Self::Ps),
            "PT" => Ok(Self::Pt),
            "PW" => Ok(Self::Pw),
            "PY" => Ok(Self::Py),
            "QA" => Ok(Self::Qa),
            "RE" => Ok(Self::Re),
            "RO" => Ok(Self::Ro),
            "RS" => Ok(Self::Rs),
            "RU" => Ok(Self::Ru),
            "RW" => Ok(Self::Rw),
            "SA" => Ok(Self::Sa),
            "SB" => Ok(Self::Sb),
            "SC" => Ok(Self::Sc),
            "SD" => Ok(Self::Sd),
            "SE" => Ok(Self::Se),
            "SG" => Ok(Self::Sg),
            "SH" => Ok(Self::Sh),
            "SI" => Ok(Self::Si),
            "SJ" => Ok(Self::Sj),
            "SK" => Ok(Self::Sk),
            "SL" => Ok(Self::Sl),
            "SM" => Ok(Self::Sm),
            "SN" => Ok(Self::Sn),
            "SO" => Ok(Self::So),
            "SR" => Ok(Self::Sr),
            "SS" => Ok(Self::Ss),
            "ST" => Ok(Self::St),
            "SV" => Ok(Self::Sv),
            "SX" => Ok(Self::Sx),
            "SY" => Ok(Self::Sy),
            "SZ" => Ok(Self::Sz),
            "TC" => Ok(Self::Tc),
            "TD" => Ok(Self::Td),
            "TF" => Ok(Self::Tf),
            "TG" => Ok(Self::Tg),
            "TH" => Ok(Self::Th),
            "TJ" => Ok(Self::Tj),
            "TK" => Ok(Self::Tk),
            "TL" => Ok(Self::Tl),
            "TM" => Ok(Self::Tm),
            "TN" => Ok(Self::Tn),
            "TO" => Ok(Self::To),
            "TR" => Ok(Self::Tr),
            "TT" => Ok(Self::Tt),
            "TV" => Ok(Self::Tv),
            "TW" => Ok(Self::Tw),
            "TZ" => Ok(Self::Tz),
            "UA" => Ok(Self::Ua),
            "UG" => Ok(Self::Ug),
            "UM" => Ok(Self::Um),
            "US" => Ok(Self::Us),
            "UY" => Ok(Self::Uy),
            "UZ" => Ok(Self::Uz),
            "VA" => Ok(Self::Va),
            "VC" => Ok(Self::Vc),
            "VE" => Ok(Self::Ve),
            "VG" => Ok(Self::Vg),
            "VI" => Ok(Self::Vi),
            "VN" => Ok(Self::Vn),
            "VU" => Ok(Self::Vu),
            "WF" => Ok(Self::Wf),
            "WS" => Ok(Self::Ws),
            "YE" => Ok(Self::Ye),
            "YT" => Ok(Self::Yt),
            "ZA" => Ok(Self::Za),
            "ZM" => Ok(Self::Zm),
            "ZW" => Ok(Self::Zw),
            other => Err(MollieError::invalid_request(format!(
                "unsupported ISO 3166-1 alpha-2 country code `{other}`"
            ))),
        }
    }
}

impl fmt::Display for CountryCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl AsRef<str> for CountryCode {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl TryFrom<&str> for CountryCode {
    type Error = MollieError;
    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::parse(value)
    }
}

impl TryFrom<String> for CountryCode {
    type Error = MollieError;
    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::parse(value)
    }
}

impl From<CountryCode> for String {
    fn from(value: CountryCode) -> Self {
        value.as_str().to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::CountryCode;

    #[test]
    fn parse_round_trips_all_codes() {
        assert_eq!(CountryCode::ALL.len(), 250);
        for code in CountryCode::ALL {
            let again = CountryCode::parse(code.as_str()).unwrap();
            assert_eq!(again, code);
            assert_eq!(again.to_string().len(), 2);
            assert!(!code.name().is_empty());
        }
    }

    #[test]
    fn official_names_and_subdivisions_samples() {
        assert_eq!(CountryCode::NL.name(), "Netherlands, Kingdom of the");
        assert_eq!(
            CountryCode::GB.name(),
            "United Kingdom of Great Britain and Northern Ireland"
        );
        assert_eq!(CountryCode::BO.name(), "Bolivia, Plurinational State of");
        assert_eq!(CountryCode::AD.subdivisions(), Some("7 parishes"));
        assert_eq!(CountryCode::AQ.subdivisions(), None);
        assert!(CountryCode::is_valid("AN")); // historical
    }

    #[test]
    fn rejects_invalid() {
        assert!(CountryCode::parse("nl").is_err());
        assert!(CountryCode::parse("NLD").is_err());
        assert!(CountryCode::parse("XX").is_err());
        assert!(CountryCode::parse("").is_err());
        assert!(CountryCode::is_valid_format("XX"));
        assert!(!CountryCode::is_valid("XX"));
    }
}
