//! Machine-readable Mollie route capabilities generated from `specs-3.0.yaml`.
//!
//! This table is the checked-in **operation safety profile** SSOT
//! ([`crate::OperationSafetyProfile`] aliases [`RouteCapability`]). Derived
//! auth/mutation/idempotency/pagination classes live on
//! [`crate::operation_safety`] methods â€” do not invent a second parallel registry.

use crate::transport::RetryClass;

/// Whether an operation has a dedicated validated request-builder facade.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RouteAccess {
    /// The SDK exposes a validated write builder for this operation.
    ValidatedFacade,
    /// Use the generated route method and request model directly.
    GeneratedClient,
}

/// Stable capability metadata for one Mollie OpenAPI operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RouteCapability {
    /// The normalized OpenAPI operation id.
    pub operation_id: &'static str,
    /// The OpenAPI tag for this operation.
    pub route_group: &'static str,
    /// The HTTP method declared by Mollie.
    pub http_method: &'static str,
    /// The Mollie API path template.
    pub path: &'static str,
    /// Whether the operation declares Mollie's `testmode` query.
    pub supports_testmode: bool,
    /// Whether sending an `Idempotency-Key` is semantically meaningful.
    pub supports_idempotency: bool,
    /// Whether the SDK may auto-retry without an explicit idempotency key.
    pub safe_to_retry: bool,
    /// Retry classification used by transport policy.
    pub retry_class: RetryClass,
    /// Whether the operation is a list/page style endpoint.
    pub paginated: bool,
    /// Whether the OpenAPI operation documents a `profileId` parameter.
    pub requires_profile_scope: bool,
    /// Whether a dedicated validated request builder exists.
    pub access: RouteAccess,
}

/// All operations in the checked-in Mollie OpenAPI contract.
pub const ROUTE_CAPABILITIES: &[RouteCapability] = &[
    RouteCapability {
        operation_id: "oauth_generate_tokens",
        route_group: "oauth_api",
        http_method: "POST",
        path: "/oauth2/tokens",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "oauth_revoke_tokens",
        route_group: "oauth_api",
        http_method: "DELETE",
        path: "/oauth2/tokens",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_balances",
        route_group: "balances_api",
        http_method: "GET",
        path: "/balances",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_balance",
        route_group: "balances_api",
        http_method: "GET",
        path: "/balances/{balanceId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_primary_balance",
        route_group: "balances_api",
        http_method: "GET",
        path: "/balances/primary",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_balance_report",
        route_group: "balances_api",
        http_method: "GET",
        path: "/balances/{balanceId}/report",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_balance_transactions",
        route_group: "balances_api",
        http_method: "GET",
        path: "/balances/{balanceId}/transactions",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_settlements",
        route_group: "settlements_api",
        http_method: "GET",
        path: "/settlements",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_settlement",
        route_group: "settlements_api",
        http_method: "GET",
        path: "/settlements/{settlementId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_open_settlement",
        route_group: "settlements_api",
        http_method: "GET",
        path: "/settlements/open",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_next_settlement",
        route_group: "settlements_api",
        http_method: "GET",
        path: "/settlements/next",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_settlement_payments",
        route_group: "settlements_api",
        http_method: "GET",
        path: "/settlements/{settlementId}/payments",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_settlement_captures",
        route_group: "settlements_api",
        http_method: "GET",
        path: "/settlements/{settlementId}/captures",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_settlement_refunds",
        route_group: "settlements_api",
        http_method: "GET",
        path: "/settlements/{settlementId}/refunds",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_settlement_chargebacks",
        route_group: "settlements_api",
        http_method: "GET",
        path: "/settlements/{settlementId}/chargebacks",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_invoices",
        route_group: "invoices_api",
        http_method: "GET",
        path: "/invoices",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_invoice",
        route_group: "invoices_api",
        http_method: "GET",
        path: "/invoices/{invoiceId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_permissions",
        route_group: "permissions_api",
        http_method: "GET",
        path: "/permissions",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_permission",
        route_group: "permissions_api",
        http_method: "GET",
        path: "/permissions/{permissionId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_organization",
        route_group: "organizations_api",
        http_method: "GET",
        path: "/organizations/{organizationId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_current_organization",
        route_group: "organizations_api",
        http_method: "GET",
        path: "/organizations/me",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_partner_status",
        route_group: "organizations_api",
        http_method: "GET",
        path: "/organizations/me/partner",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_profile",
        route_group: "profiles_api",
        http_method: "POST",
        path: "/profiles",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_profiles",
        route_group: "profiles_api",
        http_method: "GET",
        path: "/profiles",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_profile",
        route_group: "profiles_api",
        http_method: "GET",
        path: "/profiles/{profileId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "update_profile",
        route_group: "profiles_api",
        http_method: "PATCH",
        path: "/profiles/{profileId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "delete_profile",
        route_group: "profiles_api",
        http_method: "DELETE",
        path: "/profiles/{profileId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_current_profile",
        route_group: "profiles_api",
        http_method: "GET",
        path: "/profiles/me",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_onboarding_status",
        route_group: "onboarding_api",
        http_method: "GET",
        path: "/onboarding/me",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "submit_onboarding_data",
        route_group: "onboarding_api",
        http_method: "POST",
        path: "/onboarding/me",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_capabilities",
        route_group: "capabilities_api",
        http_method: "GET",
        path: "/capabilities",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_clients",
        route_group: "clients_api",
        http_method: "GET",
        path: "/clients",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_client",
        route_group: "clients_api",
        http_method: "GET",
        path: "/clients/{organizationId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_client_link",
        route_group: "client_links_api",
        http_method: "POST",
        path: "/client-links",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_webhook",
        route_group: "webhooks_api",
        http_method: "POST",
        path: "/webhooks",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_webhooks",
        route_group: "webhooks_api",
        http_method: "GET",
        path: "/webhooks",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "update_webhook",
        route_group: "webhooks_api",
        http_method: "PATCH",
        path: "/webhooks/{webhookId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_webhook",
        route_group: "webhooks_api",
        http_method: "GET",
        path: "/webhooks/{webhookId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "delete_webhook",
        route_group: "webhooks_api",
        http_method: "DELETE",
        path: "/webhooks/{webhookId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "test_webhook",
        route_group: "webhooks_api",
        http_method: "POST",
        path: "/webhooks/{webhookId}/ping",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_webhook_event",
        route_group: "webhook_events_api",
        http_method: "GET",
        path: "/events/{webhookEventId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_connect_balance_transfer",
        route_group: "balance_transfers_api",
        http_method: "POST",
        path: "/connect/balance-transfers",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_connect_balance_transfers",
        route_group: "balance_transfers_api",
        http_method: "GET",
        path: "/connect/balance-transfers",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_connect_balance_transfer",
        route_group: "balance_transfers_api",
        http_method: "GET",
        path: "/connect/balance-transfers/{balanceTransferId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_payment",
        route_group: "payments_api",
        http_method: "POST",
        path: "/payments",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_payments",
        route_group: "payments_api",
        http_method: "GET",
        path: "/payments",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_payment",
        route_group: "payments_api",
        http_method: "GET",
        path: "/payments/{paymentId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "update_payment",
        route_group: "payments_api",
        http_method: "PATCH",
        path: "/payments/{paymentId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "cancel_payment",
        route_group: "payments_api",
        http_method: "DELETE",
        path: "/payments/{paymentId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "release_authorization",
        route_group: "payments_api",
        http_method: "POST",
        path: "/payments/{paymentId}/release-authorization",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_unmatched_credit_transfers",
        route_group: "unmatched_credit_transfers_api",
        http_method: "GET",
        path: "/unmatched-credit-transfers",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_unmatched_credit_transfer",
        route_group: "unmatched_credit_transfers_api",
        http_method: "GET",
        path: "/unmatched-credit-transfers/{unmatchedCreditTransferId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "match_unmatched_credit_transfer",
        route_group: "unmatched_credit_transfers_api",
        http_method: "POST",
        path: "/unmatched-credit-transfers/{unmatchedCreditTransferId}/match",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "return_unmatched_credit_transfer",
        route_group: "unmatched_credit_transfers_api",
        http_method: "POST",
        path: "/unmatched-credit-transfers/{unmatchedCreditTransferId}/return",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "create_session",
        route_group: "sessions_api",
        http_method: "POST",
        path: "/sessions",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "get_session",
        route_group: "sessions_api",
        http_method: "GET",
        path: "/sessions/{sessionId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_methods",
        route_group: "methods_api",
        http_method: "GET",
        path: "/methods",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_all_methods",
        route_group: "methods_api",
        http_method: "GET",
        path: "/methods/all",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_method",
        route_group: "methods_api",
        http_method: "GET",
        path: "/methods/{methodId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "enable_method",
        route_group: "methods_api",
        http_method: "POST",
        path: "/profiles/{profileId}/methods/{methodId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "disable_method",
        route_group: "methods_api",
        http_method: "DELETE",
        path: "/profiles/{profileId}/methods/{methodId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "enable_method_issuer",
        route_group: "methods_api",
        http_method: "POST",
        path: "/profiles/{profileId}/methods/{methodId}/issuers/{issuerId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "disable_method_issuer",
        route_group: "methods_api",
        http_method: "DELETE",
        path: "/profiles/{profileId}/methods/{methodId}/issuers/{issuerId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_refund",
        route_group: "refunds_api",
        http_method: "POST",
        path: "/payments/{paymentId}/refunds",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_refunds",
        route_group: "refunds_api",
        http_method: "GET",
        path: "/payments/{paymentId}/refunds",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_refund",
        route_group: "refunds_api",
        http_method: "GET",
        path: "/payments/{paymentId}/refunds/{refundId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "cancel_refund",
        route_group: "refunds_api",
        http_method: "DELETE",
        path: "/payments/{paymentId}/refunds/{refundId}",
        supports_testmode: true,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_all_refunds",
        route_group: "refunds_api",
        http_method: "GET",
        path: "/refunds",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_chargebacks",
        route_group: "chargebacks_api",
        http_method: "GET",
        path: "/payments/{paymentId}/chargebacks",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_chargeback",
        route_group: "chargebacks_api",
        http_method: "GET",
        path: "/payments/{paymentId}/chargebacks/{chargebackId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_all_chargebacks",
        route_group: "chargebacks_api",
        http_method: "GET",
        path: "/chargebacks",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: true,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_capture",
        route_group: "captures_api",
        http_method: "POST",
        path: "/payments/{paymentId}/captures",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_captures",
        route_group: "captures_api",
        http_method: "GET",
        path: "/payments/{paymentId}/captures",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_capture",
        route_group: "captures_api",
        http_method: "GET",
        path: "/payments/{paymentId}/captures/{captureId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "request_apple_pay_payment_session",
        route_group: "wallets_api",
        http_method: "POST",
        path: "/wallets/applepay/sessions",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_payment_link",
        route_group: "payment_links_api",
        http_method: "POST",
        path: "/payment-links",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_payment_links",
        route_group: "payment_links_api",
        http_method: "GET",
        path: "/payment-links",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_payment_link",
        route_group: "payment_links_api",
        http_method: "GET",
        path: "/payment-links/{paymentLinkId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "update_payment_link",
        route_group: "payment_links_api",
        http_method: "PATCH",
        path: "/payment-links/{paymentLinkId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "delete_payment_link",
        route_group: "payment_links_api",
        http_method: "DELETE",
        path: "/payment-links/{paymentLinkId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_payment_link_payments",
        route_group: "payment_links_api",
        http_method: "GET",
        path: "/payment-links/{paymentLinkId}/payments",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_terminals",
        route_group: "terminals_api",
        http_method: "GET",
        path: "/terminals",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_terminal",
        route_group: "terminals_api",
        http_method: "GET",
        path: "/terminals/{terminalId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "terminals_request_pairing_code",
        route_group: "terminals_api",
        http_method: "POST",
        path: "/terminals/pairing-codes",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "terminals_list_pairing_codes",
        route_group: "terminals_api",
        http_method: "GET",
        path: "/terminals/pairing-codes",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: true,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "terminals_get_pairing_code",
        route_group: "terminals_api",
        http_method: "GET",
        path: "/terminals/pairing-codes/{pairingCodeId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "terminals_revoke_pairing_code",
        route_group: "terminals_api",
        http_method: "DELETE",
        path: "/terminals/pairing-codes/{pairingCodeId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "payment_create_route",
        route_group: "delayed_routing_api",
        http_method: "POST",
        path: "/payments/{paymentId}/routes",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "payment_list_routes",
        route_group: "delayed_routing_api",
        http_method: "GET",
        path: "/payments/{paymentId}/routes",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "payment_get_route",
        route_group: "delayed_routing_api",
        http_method: "GET",
        path: "/payments/{paymentId}/routes/{routeId}",
        supports_testmode: false,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_customer",
        route_group: "customers_api",
        http_method: "POST",
        path: "/customers",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_customers",
        route_group: "customers_api",
        http_method: "GET",
        path: "/customers",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_customer",
        route_group: "customers_api",
        http_method: "GET",
        path: "/customers/{customerId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "update_customer",
        route_group: "customers_api",
        http_method: "PATCH",
        path: "/customers/{customerId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "delete_customer",
        route_group: "customers_api",
        http_method: "DELETE",
        path: "/customers/{customerId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_customer_payment",
        route_group: "customers_api",
        http_method: "POST",
        path: "/customers/{customerId}/payments",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_customer_payments",
        route_group: "customers_api",
        http_method: "GET",
        path: "/customers/{customerId}/payments",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_mandate",
        route_group: "mandates_api",
        http_method: "POST",
        path: "/customers/{customerId}/mandates",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_mandates",
        route_group: "mandates_api",
        http_method: "GET",
        path: "/customers/{customerId}/mandates",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_mandate",
        route_group: "mandates_api",
        http_method: "GET",
        path: "/customers/{customerId}/mandates/{mandateId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "revoke_mandate",
        route_group: "mandates_api",
        http_method: "DELETE",
        path: "/customers/{customerId}/mandates/{mandateId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_subscription",
        route_group: "subscriptions_api",
        http_method: "POST",
        path: "/customers/{customerId}/subscriptions",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_subscriptions",
        route_group: "subscriptions_api",
        http_method: "GET",
        path: "/customers/{customerId}/subscriptions",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_subscription",
        route_group: "subscriptions_api",
        http_method: "GET",
        path: "/customers/{customerId}/subscriptions/{subscriptionId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "update_subscription",
        route_group: "subscriptions_api",
        http_method: "PATCH",
        path: "/customers/{customerId}/subscriptions/{subscriptionId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "cancel_subscription",
        route_group: "subscriptions_api",
        http_method: "DELETE",
        path: "/customers/{customerId}/subscriptions/{subscriptionId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_all_subscriptions",
        route_group: "subscriptions_api",
        http_method: "GET",
        path: "/subscriptions",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: true,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_subscription_payments",
        route_group: "subscriptions_api",
        http_method: "GET",
        path: "/customers/{customerId}/subscriptions/{subscriptionId}/payments",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_sales_invoice",
        route_group: "sales_invoices_api",
        http_method: "POST",
        path: "/sales-invoices",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_sales_invoices",
        route_group: "sales_invoices_api",
        http_method: "GET",
        path: "/sales-invoices",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_sales_invoice",
        route_group: "sales_invoices_api",
        http_method: "GET",
        path: "/sales-invoices/{salesInvoiceId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "update_sales_invoice",
        route_group: "sales_invoices_api",
        http_method: "PATCH",
        path: "/sales-invoices/{salesInvoiceId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "delete_sales_invoice",
        route_group: "sales_invoices_api",
        http_method: "DELETE",
        path: "/sales-invoices/{salesInvoiceId}",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_business_accounts",
        route_group: "accounts_api",
        http_method: "GET",
        path: "/business-accounts/accounts",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_business_account",
        route_group: "accounts_api",
        http_method: "GET",
        path: "/business-accounts/accounts/{businessAccountId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "list_business_account_transactions",
        route_group: "accounts_api",
        http_method: "GET",
        path: "/business-accounts/accounts/{businessAccountId}/transactions",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_business_account_transaction",
        route_group: "accounts_api",
        http_method: "GET",
        path: "/business-accounts/accounts/{businessAccountId}/transactions/{transactionId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "create_transfer",
        route_group: "transfers_api",
        http_method: "POST",
        path: "/business-accounts/transfers",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "get_transfer",
        route_group: "transfers_api",
        http_method: "GET",
        path: "/business-accounts/transfers/{businessAccountsTransferId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "verify_payee",
        route_group: "verify_payee_api",
        http_method: "POST",
        path: "/business-accounts/payee-verifications",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::NonRetryableWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "create_payout",
        route_group: "payouts_api",
        http_method: "POST",
        path: "/payouts",
        supports_testmode: false,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
    RouteCapability {
        operation_id: "list_payouts",
        route_group: "payouts_api",
        http_method: "GET",
        path: "/payouts",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: true,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "get_payout",
        route_group: "payouts_api",
        http_method: "GET",
        path: "/payouts/{payoutId}",
        supports_testmode: true,
        supports_idempotency: false,
        safe_to_retry: true,
        retry_class: RetryClass::SafeRead,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::GeneratedClient,
    },
    RouteCapability {
        operation_id: "cancel_payout",
        route_group: "payouts_api",
        http_method: "DELETE",
        path: "/payouts/{payoutId}",
        supports_testmode: true,
        supports_idempotency: true,
        safe_to_retry: false,
        retry_class: RetryClass::IdempotentWrite,
        paginated: false,
        requires_profile_scope: false,
        access: RouteAccess::ValidatedFacade,
    },
];

/// Finds an operation by its normalized OpenAPI operation id.
#[must_use]
pub fn route_capability(operation_id: &str) -> Option<&'static RouteCapability> {
    ROUTE_CAPABILITIES
        .iter()
        .find(|capability| capability.operation_id == operation_id)
}

/// Resolves retry class for a generated operation, preferring the registry.
///
/// When the operation id is not in the capability table, falls back to
/// [`crate::transport::classify_http_method`], which never treats unknown
/// writes as auto-retryable.
#[must_use]
pub fn retry_class_for_operation(operation_id: &str, http_method: &str) -> RetryClass {
    route_capability(operation_id)
        .map(|cap| cap.retry_class)
        .unwrap_or_else(|| crate::transport::classify_http_method(http_method))
}

#[cfg(test)]
mod tests {
    use super::{retry_class_for_operation, route_capability, RouteAccess, ROUTE_CAPABILITIES};
    use crate::transport::RetryClass;

    #[test]
    fn metadata_covers_every_spec_operation_once() {
        assert_eq!(ROUTE_CAPABILITIES.len(), 124);
        for (index, capability) in ROUTE_CAPABILITIES.iter().enumerate() {
            assert!(ROUTE_CAPABILITIES[index + 1..]
                .iter()
                .all(|other| { other.operation_id != capability.operation_id }));
        }
    }

    #[test]
    fn validated_write_operations_are_explicit() {
        for operation in [
            "create_payment",
            "create_refund",
            "create_subscription",
            "create_payout",
            "create_transfer",
            "verify_payee",
            "oauth_generate_tokens",
            "payment_create_route",
        ] {
            assert_eq!(
                route_capability(operation).unwrap().access,
                RouteAccess::ValidatedFacade
            );
        }
    }

    #[test]
    fn list_payments_is_safe_read() {
        let cap = route_capability("list_payments").unwrap();
        assert!(cap.safe_to_retry);
        assert_eq!(cap.retry_class, RetryClass::SafeRead);
        assert!(cap.paginated);
    }

    #[test]
    fn create_payment_supports_idempotency() {
        let cap = route_capability("create_payment").unwrap();
        assert!(cap.supports_idempotency);
        assert!(!cap.safe_to_retry);
        assert_eq!(cap.retry_class, RetryClass::IdempotentWrite);
    }

    #[test]
    fn retry_class_prefers_registry_over_method() {
        assert_eq!(
            retry_class_for_operation("create_payment", "POST"),
            RetryClass::IdempotentWrite
        );
        assert_eq!(
            retry_class_for_operation("list_payments", "GET"),
            RetryClass::SafeRead
        );
        assert_eq!(
            retry_class_for_operation("oauth_generate_tokens", "POST"),
            RetryClass::NonRetryableWrite
        );
        // Unknown operation id: method fallback must not upgrade POST.
        assert_eq!(
            retry_class_for_operation("totally_unknown_op", "POST"),
            RetryClass::Unknown
        );
    }
}
